###############################################################################
# Bare-metal screener identity.
#
# Hetzner cannot provide a Google ambient identity. This pool trusts one
# operator-owned CA and accepts only the exact URI SAN assigned to
# subnet-screener-1. The host-generated private key and leaf certificate never
# enter Terraform. The resulting service account has no project role and can
# read only the existing source-review credential.
###############################################################################

locals {
  screener_fleet_x509_subject = "spiffe://dittobench.ai/screener/subnet-screener-1"
  screener_fleet_x509_count   = var.enable_screener_fleet_x509_identity ? 1 : 0
}

# Workload Identity pool administration is not included in Project IAM Admin.
# Keep this grant in the same reviewed state as the pool instead of relying on
# a one-off console or gcloud bootstrap. The pool explicitly depends on it so
# an exact first apply cannot race the permission propagation.
resource "google_project_iam_member" "screener_fleet_x509_pool_admin" {
  count   = local.screener_fleet_x509_count
  project = var.project
  role    = "roles/iam.workloadIdentityPoolAdmin"
  member  = "serviceAccount:github-actions-terraform-apply@${var.project}.iam.gserviceaccount.com"
}

variable "enable_screener_fleet_x509_identity" {
  description = "Create the exact-subject X.509 WIF identity used by subnet-screener-1 to read its source-review secret. The host certificate private key is generated by Ansible and never enters Terraform."
  type        = bool
  default     = false
}

variable "screener_fleet_x509_ca_certificate_pem" {
  description = "Public PEM certificate for the offline CA that signs subnet-screener-1's client certificate. This is a trust anchor, not a private key."
  type        = string
  default     = ""

  validation {
    condition = (
      var.screener_fleet_x509_ca_certificate_pem == "" ||
      can(regex(
        "^-----BEGIN CERTIFICATE-----\\n(?:[A-Za-z0-9+/=]+\\n)+-----END CERTIFICATE-----\\n?$",
        var.screener_fleet_x509_ca_certificate_pem,
      ))
    )
    error_message = "screener_fleet_x509_ca_certificate_pem must be one PEM certificate with no private key."
  }
}

resource "google_service_account" "screener_fleet_x509" {
  count        = local.screener_fleet_x509_count
  project      = var.project
  account_id   = "subnet-screener-1"
  display_name = "Hetzner screener subnet-screener-1"
  description  = "X.509-federated identity; reads only validator-openrouter-key."
}

resource "google_iam_workload_identity_pool" "screener_fleet_x509" {
  count                     = local.screener_fleet_x509_count
  project                   = var.project
  workload_identity_pool_id = "screener-fleet-x509"
  display_name              = "Screener fleet X.509"
  description               = "External bare-metal screener identities issued by the Ditto offline CA."

  lifecycle {
    precondition {
      condition     = var.screener_fleet_x509_ca_certificate_pem != ""
      error_message = "Set the public screener fleet CA certificate before enabling X.509 federation."
    }
  }

  depends_on = [google_project_iam_member.screener_fleet_x509_pool_admin]
}

resource "google_iam_workload_identity_pool_provider" "screener_fleet_x509" {
  count                              = local.screener_fleet_x509_count
  project                            = var.project
  workload_identity_pool_id          = google_iam_workload_identity_pool.screener_fleet_x509[0].workload_identity_pool_id
  workload_identity_pool_provider_id = "subnet-screener-1"
  display_name                       = "subnet-screener-1"
  description                        = "Exact URI-SAN identity for the Helsinki bare-metal screener."
  attribute_mapping = {
    "google.subject" = "assertion.san.uri"
  }
  attribute_condition = "assertion.san.uri == '${local.screener_fleet_x509_subject}'"

  x509 {
    trust_store {
      trust_anchors {
        pem_certificate = var.screener_fleet_x509_ca_certificate_pem
      }
    }
  }
}

resource "google_service_account_iam_member" "screener_fleet_x509_impersonation" {
  count              = local.screener_fleet_x509_count
  service_account_id = google_service_account.screener_fleet_x509[0].name
  role               = "roles/iam.workloadIdentityUser"
  member             = "principal://iam.googleapis.com/projects/${data.google_project.this.number}/locations/global/workloadIdentityPools/${google_iam_workload_identity_pool.screener_fleet_x509[0].workload_identity_pool_id}/subject/${local.screener_fleet_x509_subject}"
}

resource "google_secret_manager_secret_iam_member" "screener_fleet_x509_source_review" {
  count     = local.screener_fleet_x509_count
  project   = var.project
  secret_id = "validator-openrouter-key"
  role      = "roles/secretmanager.secretAccessor"
  member    = google_service_account.screener_fleet_x509[0].member

  depends_on = [google_secret_manager_secret.validator_openrouter_key]
}

output "screener_fleet_x509_provider" {
  description = "Provider audience for subnet-screener-1's non-secret external-account configuration."
  value       = var.enable_screener_fleet_x509_identity ? google_iam_workload_identity_pool_provider.screener_fleet_x509[0].name : ""
}

output "screener_fleet_x509_service_account_email" {
  description = "Dedicated impersonated service account; it can read only validator-openrouter-key."
  value       = var.enable_screener_fleet_x509_identity ? google_service_account.screener_fleet_x509[0].email : ""
}

output "screener_fleet_x509_subject" {
  description = "Exact URI SAN required in the subnet-screener-1 client certificate."
  value       = var.enable_screener_fleet_x509_identity ? local.screener_fleet_x509_subject : ""
}
