FROM docker.io/library/docker:29-dind-rootless@sha256:371962f4344295a1eb185f1c9e62064bf4503a7beb8c6e73be3405500041784b

USER root
RUN apk add --no-cache socat
COPY scripts/sandbox-docker-entrypoint.sh /usr/local/bin/sandbox-docker-entrypoint
USER rootless

ENTRYPOINT ["sandbox-docker-entrypoint"]
