package datagen

import (
	"fmt"
	"sort"

	"github.com/ditto-assistant/dittobench-datagen/persona"
	"github.com/ditto-assistant/dittobench-datagen/protocol"
)

// ToolSurface is the public, read-only description of one tool category's
// prompt bank: the templates or grammar the generator renders a prompt from,
// the expected tool sequence, and the argument slot it pins. It exists so the
// generator-inverse adversary (cmd/parserprobe) can be assembled from the
// repository's own banks instead of a hand-copied mirror that would drift.
//
// Exporting the bank changes no generated bytes: it is a projection of the
// same frozen category table GenerateCasesWithFillersForVersion reads.
type ToolSurface struct {
	Category string
	// Tools is the expected tool-name sequence (empty for no-tool categories).
	Tools []string
	// Unordered mirrors category.unordered (independent parallel calls).
	Unordered bool
	// ArgKey is the RequiredArgs key pinned from the filler or intent value.
	ArgKey string
	// Templates are the %s prompt frames; empty when Grammar is set.
	Templates []string
	// Grammar is the persona.Grammar prompt source when the category uses one.
	Grammar persona.Grammar
	// Wrap reports whether the prompt passes through persona.Wrap with the
	// datagen lead-in/trailer pools (ToolPromptLeadIns / ToolPromptTrailers).
	Wrap bool
	// Intents are the intent-phrased prompts and the argument value each resolves
	// to. Under v8+ set_* categories draw exclusively from the v8 intent bank.
	Intents []ToolIntent
	// ResultUsage reports that the %s filler is the served fixture's needle
	// subject rather than a filler pool value.
	ResultUsage bool
}

// ToolIntent is one intent-phrased prompt and its resolved argument value.
type ToolIntent struct {
	Prompt string
	Value  string
}

// NamedToolGrammar exposes public rendering rules, never a sampled seed or
// grading value. Slot captures must be resolved from delivered prompt/records.
type NamedToolGrammar struct {
	Category string
	Grammar  persona.Grammar
	Slots    []string
	Value    string
}

func V13NamedToolGrammars() []NamedToolGrammar {
	out := []NamedToolGrammar{
		{"world_contact_research_email_result_usage", v13WorldContactEmailGrammar, []string{"subject", "nickname", "relation", "city", "context"}, ""},
		{"world_theme_discover_set", v13WorldThemeDiscoverGrammar, []string{"accent"}, ""},
		{"world_business_workflow", v13WorldBusinessWorkflowGrammar, []string{"alias", "client", "nickname"}, ""},
		{"v10_state_dependent_routing", v13RoutingAskGrammar, []string{"alias"}, ""},
		{V13StateDependentCalendarCategory, persona.Grammar{"root": {
			"Get the \"#alias#\" review onto my calendar for #day# afternoon.",
			"Make sure the \"#alias#\" review is on my calendar for #day#.",
			"I want the \"#alias#\" review on my calendar #day# — sort that out.",
		}}, []string{"alias", "day"}, ""},
		{V13StateDependentEmailCategory, persona.Grammar{"root": {
			"Get back to them on the \"#alias#\" numbers.",
			"Send them the \"#alias#\" numbers now.",
			"The \"#alias#\" figures are ready — get them out to them.",
		}}, []string{"alias"}, ""},
	}
	for _, intent := range v13ArgIntentGrammars["set_effort"] {
		out = append(out, NamedToolGrammar{"set_effort", intent.grammar, nil, intent.value})
	}
	for _, fact := range v13PlantedFacts {
		out = append(out, NamedToolGrammar{"v13_memory_effect_read", persona.Grammar{"root": append([]string(nil), fact.questions...)}, nil, fmt.Sprintf(fact.record, "%s")})
	}
	for _, pair := range v13Unknowables {
		for i, leads := range [][]string{v13UnknowableLeads, v13AnswerableLeads} {
			var roots []string
			for _, lead := range leads {
				text := lead + pair[i] + "?"
				if i == 1 {
					text = v13Sentence(lead + pair[i])
				}
				roots = append(roots, text)
			}
			tool := ""
			if i == 1 {
				tool = "search_web"
			}
			out = append(out, NamedToolGrammar{V13RestraintCategoryPrefix + string(v13FamilyAbstention), persona.Grammar{"root": roots}, nil, tool})
		}
	}
	for _, question := range v13GeneralKnowledge {
		for i, leads := range [][]string{v13NegationLeads, v13AffirmLeads} {
			var roots []string
			for _, lead := range leads {
				roots = append(roots, lead+question+"?")
			}
			tool := ""
			if i == 1 {
				tool = "search_web"
			}
			out = append(out, NamedToolGrammar{V13RestraintCategoryPrefix + string(v13FamilyNegation), persona.Grammar{"root": roots}, nil, tool})
		}
	}
	for _, noun := range []string{"accent", "chat font", "color mode"} {
		var roots []string
		for _, lead := range v13LeadIns {
			for _, verb := range []string{"make sure", "double-check that", "confirm", "see to it that", "check that"} {
				for _, tail := range v13Trailers {
					roots = append(roots, v13Sentence(lead+verb+" my Ditto "+noun+" is #value#"+tail))
				}
			}
		}
		out = append(out, NamedToolGrammar{V13RestraintCategoryPrefix + string(v13FamilyDeclarative), persona.Grammar{"root": roots}, []string{"value"}, noun})
	}
	for _, entry := range []struct {
		category        string
		patterns, roles []string
	}{
		{"world_memory_update", v13UpdatePrompts, []string{"alias", "client", "day"}},
		{"world_memory_delete", v13DeletePrompts, []string{"nickname", "context", "relation", "employer"}},
		{"v13_effect_update_read", v13FollowUpUpdatePrompts, []string{"alias", "client"}},
		{"v13_effect_delete_read", v13FollowUpDeletePrompts, []string{"nickname", "relation", "employer"}},
	} {
		var roots []string
		args := make([]any, len(entry.roles))
		for i, role := range entry.roles {
			args[i] = "#" + role + "#"
		}
		for _, pattern := range entry.patterns {
			root := fmt.Sprintf(pattern, args...)
			roots = append(roots, root)
			if entry.category == "world_memory_update" {
				for _, tail := range v13UpdateSecondFacts {
					roots = append(roots, root+fmt.Sprintf(tail, "#reviewer#"))
				}
			}
		}
		roles := append([]string(nil), entry.roles...)
		if entry.category == "world_memory_update" {
			roles = append(roles, "reviewer")
		}
		out = append(out, NamedToolGrammar{entry.category, persona.Grammar{"root": roots}, roles, ""})
	}
	for i := range out {
		copy := persona.Grammar{}
		for key, values := range out[i].Grammar {
			copy[key] = append([]string(nil), values...)
		}
		out[i].Grammar = copy
	}
	return out
}

// ToolSurfacesForVersion returns the category prompt banks the generator uses
// for benchVersion, sorted by category name. World-conversion families
// (world_*, v10_state_dependent_routing) are not in the source table: their
// prompts come from the coherent-world pass and are listed by
// WorldToolSurfaces.
func ToolSurfacesForVersion(benchVersion int) []ToolSurface {
	cats := categoriesForVersion(benchVersion)
	out := make([]ToolSurface, 0, len(cats))
	for _, cat := range cats {
		s := ToolSurface{
			Category:    cat.name,
			Unordered:   cat.unordered,
			ArgKey:      cat.argKey,
			Templates:   append([]string(nil), cat.templates...),
			Wrap:        cat.wrap,
			ResultUsage: IsResultUsage(cat.name),
		}
		if len(cat.tools) > 0 {
			s.Tools = append([]string(nil), cat.tools...)
		} else if cat.tool != "" {
			s.Tools = []string{cat.tool}
		}
		if cat.grammar != nil {
			s.Grammar = persona.Grammar{}
			for k, v := range cat.grammar {
				s.Grammar[k] = append([]string(nil), v...)
			}
		}
		intents := cat.intents
		if benchVersion >= protocol.BenchVersionV8 && cat.argKey != "" {
			intents = v8ArgIntents[cat.name]
		}
		for _, it := range intents {
			s.Intents = append(s.Intents, ToolIntent{Prompt: it.prompt, Value: it.value})
		}
		out = append(out, s)
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Category < out[j].Category })
	return out
}

// ToolPromptLeadIns and ToolPromptTrailers expose the wrap pools applied to
// wrap-flagged categories so an inverse parser can strip them.
func ToolPromptLeadIns() []string  { return append([]string(nil), promptLeadIns...) }
func ToolPromptTrailers() []string { return append([]string(nil), promptTrailers...) }

// WorldToolSurface describes one coherent-world tool family: the fixed prompt
// frames the world pass renders and the tool sequence it expects. Argument
// values are seed-bound (an email, a pair id, a formal project name) and must
// be resolved from the seeded world records, never from the prompt.
type WorldToolSurface struct {
	Category string
	Tools    []string
	// Frames are the prompt frames with %s / %q slots in generator order.
	Frames []string
	// ArgKeys are the RequiredArgs keys the family pins, in tool order (empty
	// string for a tool without pinned arguments).
	ArgKeys []string
}

// WorldToolSurfaces returns the world-family prompt frames for benchVersion.
// Every frame is a copy of the generator's own package-level bank (the
// worldXxxFrame vars in datagen.go), so a wording change in the generator moves
// the export with it. The v10 state-dependent routing family composes its cues
// from banks (V12RoutingCueBanks) and is listed with its v10 fixed frame.
func WorldToolSurfaces(benchVersion int) []WorldToolSurface {
	out := []WorldToolSurface{
		{
			Category: "world_contact_research_email_result_usage",
			Tools:    []string{"search_web", "gmail_send"},
			ArgKeys:  []string{"", "to,body"},
			Frames:   append([]string(nil), worldContactEmailFrames...),
		},
		{
			Category: "world_memory_delete",
			Tools:    []string{"delete_memory"},
			ArgKeys:  []string{"pair_id"},
			Frames:   []string{worldMemoryDeleteFrame},
		},
		{
			Category: "world_memory_update",
			Tools:    []string{"update_memory"},
			ArgKeys:  []string{"pair_id,content"},
			Frames:   []string{worldMemoryUpdateFrame},
		},
		{
			Category: "world_theme_discover_set",
			Tools:    []string{"discover_capabilities", "set_accent_color"},
			ArgKeys:  []string{"", "color"},
			Frames:   []string{worldThemeDiscoverSetFrame},
		},
		{
			Category: "world_business_workflow",
			Tools:    []string{"list_workflows", "create_workflow"},
			ArgKeys:  []string{"", "name,steps"},
			Frames:   []string{worldBusinessWorkflowFrame},
		},
		{
			Category: "world_link_chain_result_usage",
			Tools:    []string{"search_web", "read_links"},
			ArgKeys:  []string{"", ""},
			Frames:   []string{worldLinkChainFrame},
		},
	}
	if benchVersion >= protocol.BenchVersionV10 {
		out = append(out, WorldToolSurface{
			Category: "v10_state_dependent_routing",
			// The expected tools depend on the seeded planning note; the frame only
			// identifies the family and the project alias.
			Tools:   nil,
			ArgKeys: nil,
			Frames:  []string{v10StateDependentRoutingFrame},
		})
	}
	return out
}

// RoutingCueBanks are the component banks the v12 state-dependent routing
// family composes its prompt, planning note, and route cue from. They are
// exposed so an inverse parser can enumerate the product surface.
type RoutingCueBanks struct {
	AskLeads   []string
	AskTails   []string
	PlanLeads  []string
	PlanMids   []string
	PlanTails  []string
	RouteLeads []string
	RouteSeps  []string
}

// V12RoutingCueBanks returns copies of the v12 composition banks (frozen with
// the contract; see applyV10StateDependentActions).
func V12RoutingCueBanks() RoutingCueBanks {
	cp := func(b []string) []string { return append([]string(nil), b...) }
	return RoutingCueBanks{
		AskLeads:   cp(v12RoutingAskLeads),
		AskTails:   cp(v12RoutingAskTails),
		PlanLeads:  cp(v12RoutingPlanLeads),
		PlanMids:   cp(v12RoutingPlanMids),
		PlanTails:  cp(v12RoutingPlanTails),
		RouteLeads: cp(v12RoutingRouteLeads),
		RouteSeps:  cp(v12RoutingRouteSeps),
	}
}

// SettingValuePools returns the closed product-setting pools the generator
// pins exact arguments from: themes, main-model ids, and chat fonts. A harness
// resolving "dak-ish mode" or "JetBarins Mono" must land on one of these.
func SettingValuePools() (themes, modelIDs, fonts []string) {
	return append([]string(nil), themesPool()...), append([]string(nil), models...), append([]string(nil), chatFonts...)
}

func themesPool() []string { return themes }

// V13LinkReadGrammar exports the frozen generator grammar, without a subject
// or seed. The caller must fill slots only from its wire-visible prompt.
func V13LinkReadGrammar() persona.Grammar {
	out := persona.Grammar{}
	for key, values := range v13WorldLinkReadGrammar {
		out[key] = append([]string(nil), values...)
	}
	return out
}

// V13UnexpectedSurfaces exposes the same frozen frames used by the generator.
// The inverse identifies a call, not the answer returned by that call.
func V13UnexpectedSurfaces() []ToolSurface {
	var out []ToolSurface
	for _, entry := range []struct{ family, tool string }{
		{"schedules_result_usage", "list_schedules"},
		{"tool_registry_result_usage", "search_tools"},
		{"sandbox_result_usage", "run_code"},
		{"agent_jobs_result_usage", "list_agent_jobs"},
	} {
		out = append(out, ToolSurface{Category: entry.family, Tools: []string{entry.tool}, Templates: append([]string(nil), v13UnexpectedPrompts[entry.family]...), ResultUsage: true})
	}
	return out
}

type DiscoverySurface struct {
	Category, Tool, ArgKey string
	NearMiss               bool
	Templates              []string
}

// V13DiscoverySurfaces is a seed-free grammar projection. Available options
// must still be discovered by calling the served tool, not inferred from seed.
func V13DiscoverySurfaces() []DiscoverySurface {
	var out []DiscoverySurface
	for _, kind := range []string{"accent", "font"} {
		tool, key := "set_accent_color", "color"
		if kind == "font" {
			tool, key = "set_chat_font", "font"
		}
		out = append(out,
			DiscoverySurface{Category: "discovery_" + kind + "_set", Tool: tool, ArgKey: key, Templates: append([]string(nil), v13DiscoveryPrompts[kind]...)},
			DiscoverySurface{Category: "discovery_" + kind + "_set", Tool: tool, ArgKey: key, NearMiss: true, Templates: append([]string(nil), v13NearMissPrompts[kind]...)})
	}
	return out
}
