---
screener_partition_activate: false
screener_partition_worker_units:
  - ditto-screener-worker@1.service
  - ditto-screener-worker@2.service
  - ditto-screener-worker@3.service
  - ditto-screener-worker@4.service
screener_partition_prepare_only: false
