// Command catalogmirror regenerates every hand-maintained mirror of the
// DittoBench tool catalog from catalog.CatalogForVersion, so the starter kit,
// the screener's behavioral oracle, and the OpenClaw wire adapter never drift
// from the surface a scored run advertises (issue #1580 acceptance).
//
//	go run ./cmd/catalogmirror -bench-version 13 -format rust     # miners/dittobench-starter-kit/src/catalog.rs
//	go run ./cmd/catalogmirror -bench-version 13 -format python   # workers/screener/ditto_screener/policy.py _ORACLE_TOOL_NAMES
//	go run ./cmd/catalogmirror -bench-version 13 -format openclaw # services/dittobench-api/integrations/openclaw/plugin/*.json TOOL_NAMES
//
// The mirrors carry the seed-free PRODUCTION surface: per-seed decoys are
// advertised only on the scored wire (catalog.CatalogForSeed) and served by the
// validator's mock endpoint, so a mirror that named them would be wrong on every
// other seed. Run `cargo fmt` after writing the Rust mirror.
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"sort"
	"strings"

	"github.com/ditto-assistant/dittobench-datagen/catalog"
	"github.com/ditto-assistant/dittobench-datagen/protocol"
)

func main() {
	version := flag.Int("bench-version", protocol.BenchVersionV13, "benchmark contract version to mirror")
	format := flag.String("format", "rust", "rust | python | openclaw | names")
	flag.Parse()
	if !protocol.SupportedBenchVersion(*version) {
		fmt.Fprintf(os.Stderr, "catalogmirror: unsupported bench_version %d\n", *version)
		os.Exit(2)
	}
	tools := catalog.CatalogForVersion(*version)
	var out string
	var err error
	switch *format {
	case "rust":
		out, err = renderRust(*version, tools)
	case "python":
		out = renderPython(*version, tools)
	case "openclaw":
		out = renderOpenClaw(tools)
	case "names":
		out = strings.Join(catalog.ProductionToolNames(*version), "\n") + "\n"
	default:
		err = fmt.Errorf("unknown format %q", *format)
	}
	if err != nil {
		fmt.Fprintln(os.Stderr, "catalogmirror:", err)
		os.Exit(1)
	}
	fmt.Print(out)
}

type schemaProperty struct {
	Type        string   `json:"type"`
	Description string   `json:"description"`
	Enum        []string `json:"enum"`
	Items       *struct {
		Type string `json:"type"`
	} `json:"items"`
}

type toolSchema struct {
	Properties map[string]schemaProperty `json:"properties"`
	Required   []string                  `json:"required"`
}

func rustString(s string) string {
	return `"` + strings.NewReplacer(`\`, `\\`, `"`, `\"`).Replace(s) + `"`
}

func rustStrSlice(values []string) string {
	parts := make([]string, len(values))
	for i, v := range values {
		parts[i] = rustString(v)
	}
	return "&[" + strings.Join(parts, ", ") + "]"
}

// renderRust emits the complete catalog.rs for the starter kit, including its
// tests, in the kit's own helper style (`strings(...)` for string-only schemas,
// `schema(...)` otherwise; `SchemaType::Enum` for closed value lists).
func renderRust(version int, tools []protocol.ToolDefinition) (string, error) {
	var b strings.Builder
	fmt.Fprintf(&b, `//! The DittoBench v%d tool catalog — the seed-free PRODUCTION surface the
//! scored run advertises (per-seed coined decoys are added only on the scored
//! wire by the validator and are never part of this mirror). It intentionally
//! excludes the retired v7 workflow, automation, recipe, and job-status tools
//! and the v13-retired set_main_model, so local practice presents exactly the
//! product surface scored by the active benchmark.
//!
//! GENERATED by "go run ./cmd/catalogmirror -bench-version %d -format rust"
//! (research/dittobench-datagen) from catalog.CatalogForVersion; regenerate
//! there instead of editing by hand, then run "cargo fmt".

use serde_json::{json, Value};

use crate::protocol::ToolDefWire;

#[derive(Clone, Copy)]
enum SchemaType {
    String,
    StringArray,
    Array,
    Integer,
    Boolean,
    /// A closed value list rendered as a JSON-schema enum (bench v13+).
    Enum(&'static [&'static str]),
}

#[derive(Clone, Copy)]
struct Prop {
    name: &'static str,
    kind: SchemaType,
    description: &'static str,
}

fn prop(name: &'static str, kind: SchemaType, description: &'static str) -> Prop {
    Prop {
        name,
        kind,
        description,
    }
}

fn schema(props: &[Prop], required: &[&str]) -> Value {
    let mut properties = serde_json::Map::new();
    for prop in props {
        let value = match prop.kind {
            SchemaType::String => {
                json!({"type": "string", "description": prop.description})
            }
            SchemaType::StringArray => json!({
                "type": "array",
                "items": {"type": "string"},
                "description": prop.description,
            }),
            SchemaType::Array => {
                json!({"type": "array", "description": prop.description})
            }
            SchemaType::Integer => {
                json!({"type": "integer", "description": prop.description})
            }
            SchemaType::Boolean => {
                json!({"type": "boolean", "description": prop.description})
            }
            SchemaType::Enum(values) => json!({
                "type": "string",
                "description": prop.description,
                "enum": values,
            }),
        };
        properties.insert(prop.name.to_string(), value);
    }
    let mut out = serde_json::Map::new();
    out.insert("type".to_string(), json!("object"));
    out.insert("properties".to_string(), Value::Object(properties));
    if !required.is_empty() {
        out.insert("required".to_string(), json!(required));
    }
    Value::Object(out)
}

fn strings(props: &[(&'static str, &'static str)], required: &[&str]) -> Value {
    let props = props
        .iter()
        .map(|(name, description)| prop(name, SchemaType::String, description))
        .collect::<Vec<_>>();
    schema(&props, required)
}

fn tool(name: &str, description: &str, parameters: Value) -> ToolDefWire {
    ToolDefWire {
        name: name.to_string(),
        description: description.to_string(),
        parameters,
    }
}

pub fn catalog() -> Vec<ToolDefWire> {
    vec![
`, version, version)
	enumTools := map[string][]string{}
	for _, tool := range tools {
		var s toolSchema
		if err := json.Unmarshal(tool.Parameters, &s); err != nil {
			return "", fmt.Errorf("%s: %w", tool.Name, err)
		}
		keys := make([]string, 0, len(s.Properties))
		for k := range s.Properties {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		allPlainStrings := true
		for _, k := range keys {
			p := s.Properties[k]
			if p.Type != "string" || len(p.Enum) > 0 {
				allPlainStrings = false
			}
		}
		fmt.Fprintf(&b, "        tool(\n            %s,\n            %s,\n", rustString(tool.Name), rustString(tool.Description))
		if allPlainStrings {
			pairs := make([]string, 0, len(keys))
			for _, k := range keys {
				pairs = append(pairs, fmt.Sprintf("(%s, %s)", rustString(k), rustString(s.Properties[k].Description)))
			}
			fmt.Fprintf(&b, "            strings(&[%s], %s),\n", strings.Join(pairs, ", "), rustStrSlice(s.Required))
		} else {
			props := make([]string, 0, len(keys))
			for _, k := range keys {
				p := s.Properties[k]
				kind := ""
				switch {
				case p.Type == "string" && len(p.Enum) > 0:
					kind = "SchemaType::Enum(" + rustStrSlice(p.Enum) + ")"
					enumTools[tool.Name+"."+k] = p.Enum
				case p.Type == "string":
					kind = "SchemaType::String"
				case p.Type == "array" && p.Items != nil && p.Items.Type == "string":
					kind = "SchemaType::StringArray"
				case p.Type == "array":
					kind = "SchemaType::Array"
				case p.Type == "integer":
					kind = "SchemaType::Integer"
				case p.Type == "boolean":
					kind = "SchemaType::Boolean"
				default:
					return "", fmt.Errorf("%s.%s: unsupported schema type %q", tool.Name, k, p.Type)
				}
				props = append(props, fmt.Sprintf("prop(%s, %s, %s)", rustString(k), kind, rustString(p.Description)))
			}
			fmt.Fprintf(&b, "            schema(&[%s], %s),\n", strings.Join(props, ", "), rustStrSlice(s.Required))
		}
		b.WriteString("        ),\n")
	}
	b.WriteString("    ]\n}\n")

	names := make([]string, 0, len(tools))
	for _, tool := range tools {
		names = append(names, tool.Name)
	}
	enumKeys := make([]string, 0, len(enumTools))
	for k := range enumTools {
		enumKeys = append(enumKeys, k)
	}
	sort.Strings(enumKeys)
	fmt.Fprintf(&b, `
#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn catalog_matches_active_v%d_surface() {
        let catalog = catalog();
        assert_eq!(catalog.len(), %d);
        let names = catalog
            .iter()
            .map(|tool| tool.name.as_str())
            .collect::<Vec<_>>();
        assert_eq!(names, vec!%s);
    }

    #[test]
    fn catalog_uses_current_argument_shapes() {
        let catalog = catalog();
        let named = |name: &str| {
            catalog
                .iter()
                .find(|tool| tool.name == name)
                .unwrap_or_else(|| panic!("missing tool {name}"))
        };

        assert_eq!(
            named("read_links").parameters["properties"]["urls"]["type"],
            "array"
        );
        assert_eq!(
            named("search_web").parameters["properties"]["queries"]["type"],
            "array"
        );
        assert_eq!(
            named("fetch_memories").parameters["properties"]["pairIds"]["type"],
            "array"
        );
        assert_eq!(
            named("create_workflow").parameters["required"],
            json!(["name", "steps"])
        );
        assert_eq!(
            named("list_agent_jobs").parameters["properties"]["limit"]["type"],
            "integer"
        );
`, version, len(tools), rustVecLiteral(names))
	for _, k := range enumKeys {
		parts := strings.SplitN(k, ".", 2)
		fmt.Fprintf(&b, `        assert_eq!(
            named(%s).parameters["properties"][%s]["enum"],
            json!(%s)
        );
`, rustString(parts[0]), rustString(parts[1]), jsonArray(enumTools[k]))
	}
	b.WriteString(`        for retired in [
            "execute_agent_workflow",
            "get_agent_job_status",
            "create_automation",
            "list_automations",
            "create_recipe",
            "apply_recipe",
            "set_main_model",
        ] {
            assert!(
                catalog.iter().all(|tool| tool.name != retired),
                "catalog still advertises retired tool {retired}"
            );
        }
    }

    #[test]
    fn every_tool_has_an_object_schema() {
        for tool in catalog() {
            assert_eq!(tool.parameters["type"], "object", "tool {}", tool.name);
            assert!(
                tool.parameters.get("properties").is_some(),
                "tool {}",
                tool.name
            );
        }
    }
}
`)
	return b.String(), nil
}

// rustVecLiteral renders a vec![...] of string literals.
func rustVecLiteral(values []string) string {
	parts := make([]string, len(values))
	for i, v := range values {
		parts[i] = rustString(v)
	}
	return "[" + strings.Join(parts, ", ") + "]"
}

func jsonArray(values []string) string {
	raw, _ := json.Marshal(values)
	return string(raw)
}

// renderPython emits the screener oracle's _ORACLE_TOOL_NAMES block.
func renderPython(version int, tools []protocol.ToolDefinition) string {
	var b strings.Builder
	fmt.Fprintf(&b, `# The full production tool catalog by name (dittobench-datagen
# catalog.CatalogForVersion(%d), seed-free surface). The oracle offers the SAME
# catalog a scored tool case does, so tool count and names are not a tell; a
# two-tool oracle was trivially separable from scored traffic. Per-seed coined
# decoys are advertised only on the scored wire and are deliberately absent
# here. A generic query/argument schema is sufficient because the harness only
# needs the names to declare tools to the model.
# GENERATED by research/dittobench-datagen:
#   go run ./cmd/catalogmirror -bench-version %d -format python
_ORACLE_TOOL_NAMES: tuple[str, ...] = (
`, version, version)
	for _, tool := range tools {
		fmt.Fprintf(&b, "    %q,\n", tool.Name)
	}
	b.WriteString(")\n")
	return b.String()
}

// renderOpenClaw emits the plugin manifest's contracts.tools array (also the
// TOOL_NAMES constant in index.js), four names per line.
func renderOpenClaw(tools []protocol.ToolDefinition) string {
	var b strings.Builder
	b.WriteString("[\n")
	for i := 0; i < len(tools); i += 4 {
		end := i + 4
		if end > len(tools) {
			end = len(tools)
		}
		parts := make([]string, 0, 4)
		for _, tool := range tools[i:end] {
			parts = append(parts, fmt.Sprintf("%q", tool.Name))
		}
		b.WriteString("      " + strings.Join(parts, ", "))
		if end < len(tools) {
			b.WriteString(",")
		}
		b.WriteString("\n")
	}
	b.WriteString("    ]\n")
	return b.String()
}
