---
screener_capacity_environment: prod
screener_capacity_platform_url: https://platform-api.heyditto.ai
screener_capacity_gce_project: ditto-app-dev
screener_capacity_gce_region: us-central1
screener_capacity_gce_mig: ditto-screener-fleet
