"""Stock-kit file exclusion: the 2026-07-20 copy-hold regressions.

Two real holds from the same afternoon, both opened by the lexical channel with
the same 21 byte-identical starter-kit files between the pair, and only one of
them a copy:

* FALSE POSITIVE — ``bf57c7ea`` (FOREVER v3) held against ``6334962e``
  (F1rst v1), different coldkeys. Recorded evidence: ``jaccard 0.703,
  containment 0.954``. The one file carrying miner work, ``src/baseline.rs``,
  was *not* shared (0.9062 similar, +231/-11 against a kit file both forked);
  prompt jaccard was 0.320. What crossed the 0.95 containment bar was the
  unmodified kit itself — ``Cargo.lock`` (5,439 lines) and
  ``fixtures/models/cross-encoder-vocab.txt`` (30,522 lines) alone are ~366KB of
  identical text neither miner wrote. Window subtraction did not neutralize it
  because both miners forked a kit revision the shingle bundles do not contain.
* TRUE POSITIVE — ``16eddfaf`` (beking-v1) against ``81266c17`` (gggggggg v3),
  different coldkeys, 67 minutes apart. Recorded evidence: ``jaccard 0.969,
  containment 0.988``, prompt jaccard 1.000. Same 21 identical kit files, but
  here ``src/baseline.rs`` is itself near-verbatim: 0.9943 similar, +6/-10 out of
  1,408 lines.

The fixtures below reproduce that shape: identical kit content on both sides,
and the discriminator moved entirely into the authored file. The kit revision is
installed in the *digest* set but deliberately kept out of the *shingle* corpus
(except the file both miners edited, whose kit ancestor the corpus does contain —
that is the case window subtraction already handled), which is exactly the
production configuration that produced the false positive.
"""

from __future__ import annotations

import hashlib
import io
import tarfile
from array import array
from datetime import UTC, datetime, timedelta
from uuid import uuid4

import pytest

import ditto.api_server.fingerprint as fingerprint_module
from ditto.api_models.agent_status import AgentStatus
from ditto.api_server.fingerprint import (
    _file_shingles,
    _normalized_source,
    _normalized_source_shingles,
    _prompt_shingles,
    compute_content_fingerprint,
    compute_normalized_source_hash,
    compute_prompt_fingerprint,
    content_similarity,
    is_generated_lockfile,
    is_stock_kit_content,
)
from ditto.api_server.scoring_gate import (
    _DEFAULT_CONTAINMENT_TOL,
    _DEFAULT_JACCARD_TOL,
    ReviewDecision,
    evaluate_duplicate_signals,
)
from ditto.db.queries.scores import LedgerRow

_REFERENCE_SEEN = datetime(2026, 7, 18, 4, 9, 43, tzinfo=UTC)
_CANDIDATE_SEEN = _REFERENCE_SEEN + timedelta(days=2)

# --- kit content at the revision both miners forked --------------------------
# Bulk unauthored text, sized in the same ratio as production: the kit's
# generated lockfile and model vocabulary dwarf the one file a miner writes.
_KIT_LOCKFILE = (
    "# This file is automatically @generated by Cargo.\n"
    + "".join(
        f'[[package]]\nname = "crate_{i}"\nversion = "0.{i}.0"\nchecksum = "{i:064x}"\n'
        for i in range(900)
    )
).encode()
_KIT_VOCAB = "".join(f"token_{i}\n" for i in range(4000)).encode()
_KIT_README = "".join(
    f"Starter kit documentation line {i} explaining the harness contract.\n"
    for i in range(600)
).encode()
_KIT_MODULE = (
    'const KIT_PROMPT: &str = r#"You are the reference DittoBench harness. '
    "Load the supplied inputs, validate every required field, and return the "
    'standard structured response without inventing facts."#;\n'
    + "".join(
        f"fn kit_helper_{i}(x: i64) -> i64 {{\n    let y = x + {i};\n    y * 3\n}}\n"
        for i in range(80)
    )
).encode()
# The file miners actually edit. Its kit ancestor IS in the shingle corpus, so
# the kit lines inside an edited copy wash out the way they always have.
_KIT_BASELINE = "".join(
    f"    let kit_step_{i} = retrieve(query, {i}).await?;\n" for i in range(700)
).encode()

_STOCK_KIT_FILES = {
    "fixtures/models/cross-encoder-vocab.txt": _KIT_VOCAB,
    "README.md": _KIT_README,
    "src/catalog.rs": _KIT_MODULE,
    "src/baseline.rs": _KIT_BASELINE,
}


def _authored(tag: str, prompt: str, lines: int = 240) -> bytes:
    """A miner's own additions to the kit baseline: distinctive per ``tag``."""
    body = "".join(
        f"    let {tag}_rank_{i} = score_{tag}(candidate, {i}) * {i + 2};\n"
        for i in range(lines)
    )
    return f'const PROMPT: &str = r#"{prompt}"#;\n{body}'.encode()


_PROMPT_A = (
    "Rank memories by recency weighted against subject overlap, then keep only "
    "evidence tied to the current conversation before composing a grounded answer."
)
_PROMPT_B = (
    "Build a graph of recent entities, traverse verified relationships twice, then "
    "summarize the strongest supported path without adding any assumption."
)


def _tar_gz(files: dict[str, bytes]) -> bytes:
    buf = io.BytesIO()
    with tarfile.open(fileobj=buf, mode="w:gz") as tar:
        for name, data in files.items():
            info = tarfile.TarInfo(name=name)
            info.size = len(data)
            tar.addfile(info, io.BytesIO(data))
    return buf.getvalue()


def _artifact(authored_baseline: bytes) -> bytes:
    """One miner's submission: the untouched kit plus their edited baseline."""
    files = dict(_STOCK_KIT_FILES)
    files["src/baseline.rs"] = _KIT_BASELINE + authored_baseline
    # Regenerated by cargo, so it differs from the published kit lockfile and is
    # not in the digest set — yet is byte-identical between independent miners.
    files["Cargo.lock"] = _KIT_LOCKFILE + b'[[package]]\nname = "local"\n'
    return _tar_gz(files)


def _digest_sets(
    blobs: tuple[bytes, ...],
) -> tuple[frozenset[str], frozenset[str], str]:
    exact = {hashlib.sha256(blob).hexdigest() for blob in blobs}
    normalized = {
        hashlib.sha256(_normalized_source(blob).encode()).hexdigest() for blob in blobs
    }
    return (frozenset(exact), frozenset(normalized), "test-kit-digests")


@pytest.fixture
def kit_reference(monkeypatch: pytest.MonkeyPatch) -> None:
    """Install the published kit as production has it.

    Digest set: every kit file, including the revisions of them the shingle
    bundles never saw. Shingle corpus: only the baseline the miners edited —
    modelling that both miners forked a kit revision predating the bundles.
    """
    monkeypatch.setattr(
        fingerprint_module,
        "_kit_digests",
        lambda: _digest_sets(tuple(_STOCK_KIT_FILES.values())),
    )
    corpus = {
        "lexical": array(
            "Q", sorted(int(s, 16) for s in _file_shingles(_KIT_BASELINE))
        ),
        "normalized": array(
            "Q", sorted(int(s, 16) for s in _normalized_source_shingles(_KIT_BASELINE))
        ),
        "prompt": array(
            "Q", sorted(int(s, 16) for s in _prompt_shingles(_KIT_BASELINE))
        ),
    }
    monkeypatch.setattr(fingerprint_module, "_reference_shingles", corpus.__getitem__)


def _disable_kit_exclusion(monkeypatch: pytest.MonkeyPatch) -> None:
    """Restore the pre-fix behavior: window subtraction only, nothing dropped.

    Applied from inside a test body rather than as a fixture: it has to land
    *after* ``kit_reference``, and fixture resolution order between a class-level
    ``usefixtures`` and a method-level one is not something to bet a regression
    test on.
    """
    monkeypatch.setattr(
        fingerprint_module,
        "_kit_digests",
        lambda: (frozenset(), frozenset(), "empty"),
    )
    monkeypatch.setattr(fingerprint_module, "_GENERATED_LOCKFILES", frozenset())


@pytest.mark.usefixtures("kit_reference")
class TestIndependentForksClear:
    """FOREVER v3 vs F1rst v1: same kit, different work, must not hold."""

    def test_lexical_channel_is_below_both_thresholds(self) -> None:
        a = compute_content_fingerprint(_artifact(_authored("alpha", _PROMPT_A)))
        b = compute_content_fingerprint(_artifact(_authored("beta", _PROMPT_B, 260)))

        jaccard, containment = content_similarity(a, b)

        assert jaccard < _DEFAULT_JACCARD_TOL
        assert containment < _DEFAULT_CONTAINMENT_TOL

    def test_prompt_channel_separates_the_pair(self) -> None:
        """Production measured 0.320 here for the honest pair, 1.000 for the copy."""
        a = compute_prompt_fingerprint(_artifact(_authored("alpha", _PROMPT_A)))
        b = compute_prompt_fingerprint(_artifact(_authored("beta", _PROMPT_B, 260)))

        jaccard, containment = content_similarity(a, b)

        assert jaccard < _DEFAULT_JACCARD_TOL
        assert containment < _DEFAULT_CONTAINMENT_TOL

    def test_pre_fix_behavior_did_hold_this_pair(
        self, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        """Without file exclusion the same two artifacts cross the hold bar.

        This is the bug, reproduced: the shared bulk is the kit's own lockfile
        and vocabulary, and neither miner wrote a line of it.
        """
        _disable_kit_exclusion(monkeypatch)
        a = compute_content_fingerprint(_artifact(_authored("alpha", _PROMPT_A)))
        b = compute_content_fingerprint(_artifact(_authored("beta", _PROMPT_B, 260)))

        _, containment = content_similarity(a, b)

        assert containment >= _DEFAULT_CONTAINMENT_TOL

    def test_a_lone_unmodified_fork_sketches_empty(self) -> None:
        """Shipping the kit unchanged leaves nothing to compare in either direction."""
        sketch = compute_content_fingerprint(_tar_gz(dict(_STOCK_KIT_FILES)))

        assert sketch is not None
        assert sketch["m"] == []


@pytest.mark.usefixtures("kit_reference")
class TestNearVerbatimCopyStillHolds:
    """beking-v1 vs gggggggg v3: the authored file itself is the shared part."""

    # 1,400 authored lines with 6 changed: the production shape (+6/-10 out of
    # 1,408, similarity 0.9943).
    _VICTIM_LINES = 1400
    _EDITS = 6

    @classmethod
    def _victim(cls) -> bytes:
        return _authored("victim", _PROMPT_A, cls._VICTIM_LINES)

    @classmethod
    def _stolen(cls) -> bytes:
        """The victim's authored block with a handful of lines renamed."""
        lines = cls._victim().decode().splitlines()
        for i in range(cls._EDITS):
            # Never index 0: that is the prompt const, and a copier who rewrote
            # the prompt would be a different case (the prompt channel's).
            lines[(i * 211 + 7) % (len(lines) - 1) + 1] = f"    let renamed_{i} = 0;"
        return ("\n".join(lines) + "\n").encode()

    def test_lightly_edited_copy_is_still_caught(self) -> None:
        original = compute_content_fingerprint(_artifact(self._victim()))
        copy = compute_content_fingerprint(_artifact(self._stolen()))

        jaccard, containment = content_similarity(original, copy)

        assert (
            jaccard >= _DEFAULT_JACCARD_TOL or containment >= _DEFAULT_CONTAINMENT_TOL
        )

    def test_copy_padded_with_the_whole_kit_is_still_caught(self) -> None:
        """Excluding the kit removes the padding a copier would dilute Jaccard with."""
        original = compute_content_fingerprint(_artifact(self._victim()))
        padded_files = dict(_STOCK_KIT_FILES)
        padded_files["src/baseline.rs"] = _KIT_BASELINE + self._stolen()
        padded_files["Cargo.lock"] = _KIT_LOCKFILE
        padded_files["vendor/extra.txt"] = _KIT_VOCAB
        copy = compute_content_fingerprint(_tar_gz(padded_files))

        _, containment = content_similarity(original, copy)

        assert containment >= _DEFAULT_CONTAINMENT_TOL

    def test_copied_prompt_still_matches(self) -> None:
        original = compute_prompt_fingerprint(_artifact(self._victim()))
        copy = compute_prompt_fingerprint(_artifact(self._stolen()))

        jaccard, _ = content_similarity(original, copy)

        assert jaccard >= _DEFAULT_JACCARD_TOL


@pytest.mark.usefixtures("kit_reference")
class TestExclusionIsContentKeyed:
    """A denylist by name would erase real work; content keying does not."""

    def test_edited_kit_file_still_counts_as_shared_evidence(self) -> None:
        """Two miners shipping the same *edited* ``src/catalog.rs`` still match."""
        edit = b"\nfn tuned_rerank(x: i64) -> i64 { x.rotate_left(7) ^ 0xA5 }\n" * 4
        files = dict(_STOCK_KIT_FILES)
        files["src/catalog.rs"] = _KIT_MODULE + edit
        sketch = compute_content_fingerprint(_tar_gz(files))

        assert sketch is not None
        assert sketch["m"] != []
        assert content_similarity(sketch, sketch)[1] == 1.0

    def test_renaming_an_untouched_kit_file_gains_nothing(self) -> None:
        renamed = {f"vendor/{name}": data for name, data in _STOCK_KIT_FILES.items()}
        sketch = compute_content_fingerprint(_tar_gz(renamed))

        assert sketch is not None
        assert sketch["m"] == []

    def test_reformatted_kit_file_is_still_stock(self) -> None:
        reformatted = _KIT_MODULE.replace(b"    let", b"\t  let").replace(
            b"\n", b"\n\n"
        )

        assert is_stock_kit_content(reformatted)

    def test_authored_source_is_never_stock(self) -> None:
        assert not is_stock_kit_content(_authored("alpha", _PROMPT_A))


@pytest.mark.usefixtures("kit_reference")
class TestGateOutcomeOnBothProductionPairs:
    """End to end through the score-path gate, not just the thresholds.

    Both artifacts in each pair are packed the same way, so the *only* thing
    deciding the hold is what the fingerprints were computed over.
    """

    @staticmethod
    def _ledger_row(tar: bytes, *, composite: float, sha: str) -> LedgerRow:
        return LedgerRow(
            miner_hotkey="5Incumbent",
            agent_id=uuid4(),
            composite=composite,
            tool_mean=composite,
            memory_mean=composite,
            first_seen=_REFERENCE_SEEN,
            sha256=sha,
            size_bytes=len(tar),
            run_id="run_1",
            seed=42,
            validator_hotkey="5Validator",
            signature="ab" * 64,
            status=AgentStatus.SCORED,
            miner_coldkey="5IncumbentCold",
            content_fingerprint=compute_content_fingerprint(tar),
            structural_fingerprint=None,
            normalized_source_hash=compute_normalized_source_hash(tar),
            prompt_fingerprint=compute_prompt_fingerprint(tar),
        )

    @classmethod
    def _decide(cls, candidate: bytes, reference: bytes) -> ReviewDecision:
        row = cls._ledger_row(reference, composite=0.8100, sha="aa" * 32)
        return evaluate_duplicate_signals(
            agent_id=uuid4(),
            miner_hotkey="5Challenger",
            miner_coldkey="5ChallengerCold",
            submitted_at=_CANDIDATE_SEEN,
            sha256="bb" * 32,
            # The recorded composite delta of the false-positive pair (0.0108),
            # which is inside the legacy score window — so nothing but the
            # fingerprints can be doing the work here.
            composite=0.8208,
            size_bytes=len(candidate),
            eligible=[row],
            content_fingerprint=compute_content_fingerprint(candidate),
            normalized_source_hash=compute_normalized_source_hash(candidate),
            prompt_fingerprint=compute_prompt_fingerprint(candidate),
        )

    def test_independent_forks_are_not_held(self) -> None:
        decision = self._decide(
            _artifact(_authored("alpha", _PROMPT_A)),
            _artifact(_authored("beta", _PROMPT_B, 260)),
        )

        assert decision.held is False
        assert decision.duplicate_of is None

    def test_near_verbatim_copy_is_held(self) -> None:
        decision = self._decide(
            _artifact(TestNearVerbatimCopyStillHolds._stolen()),
            _artifact(TestNearVerbatimCopyStillHolds._victim()),
        )

        assert decision.held is True
        assert decision.reason is not None
        assert decision.reason.startswith("content near-duplicate")

    def test_unmodified_kit_forks_do_not_fall_through_to_size(self) -> None:
        """Two miners who shipped the kit unchanged are not held on size proximity.

        Their sketches are versioned-empty rather than absent, which is what
        keeps the legacy archive-size fallback from firing on a pair whose
        archives are necessarily the same size.
        """
        kit_only = _tar_gz(dict(_STOCK_KIT_FILES))

        decision = self._decide(kit_only, kit_only)

        assert decision.held is False


class TestGeneratedLockfiles:
    def test_known_lockfiles_are_recognized_at_any_depth(self) -> None:
        assert is_generated_lockfile("Cargo.lock")
        assert is_generated_lockfile("nested/crate/Cargo.lock")
        assert is_generated_lockfile("uv.lock")

    def test_manifests_and_source_are_not_lockfiles(self) -> None:
        assert not is_generated_lockfile("Cargo.toml")
        assert not is_generated_lockfile("src/lock.rs")
        assert not is_generated_lockfile("locked.json")
