/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthenticatedValidatorSlotsRouteImport } from './routes/_authenticated/validator-slots'
import { Route as AuthenticatedSubmissionSettingsRouteImport } from './routes/_authenticated/submission-settings'
import { Route as AuthenticatedScreeningQuarantineRouteImport } from './routes/_authenticated/screening-quarantine'
import { Route as AuthenticatedScreenerReviewSettingsRouteImport } from './routes/_authenticated/screener-review-settings'
import { Route as AuthenticatedScreenerCapacityRouteImport } from './routes/_authenticated/screener-capacity'
import { Route as AuthenticatedScoreOutliersRouteImport } from './routes/_authenticated/score-outliers'
import { Route as AuthenticatedMinerFeesRouteImport } from './routes/_authenticated/miner-fees'
import { Route as AuthenticatedInferenceRoutingRouteImport } from './routes/_authenticated/inference-routing'
import { Route as AuthenticatedInferenceConcurrencyRouteImport } from './routes/_authenticated/inference-concurrency'
import { Route as AuthenticatedCopyReviewRouteImport } from './routes/_authenticated/copy-review'
import { Route as AuthenticatedContinualRetestsRouteImport } from './routes/_authenticated/continual-retests'
import { Route as AuthenticatedBenchmarkRolloutRouteImport } from './routes/_authenticated/benchmark-rollout'
import { Route as AuthenticatedArtifactReleaseRouteImport } from './routes/_authenticated/artifact-release'
import { Route as AuthenticatedScreeningQuarantineIndexRouteImport } from './routes/_authenticated/screening-quarantine.index'
import { Route as AuthenticatedScreeningQuarantineHistoryRouteImport } from './routes/_authenticated/screening-quarantine.history'
import { Route as AuthenticatedScreeningQuarantineDisputesRouteImport } from './routes/_authenticated/screening-quarantine.disputes'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedValidatorSlotsRoute =
  AuthenticatedValidatorSlotsRouteImport.update({
    id: '/validator-slots',
    path: '/validator-slots',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSubmissionSettingsRoute =
  AuthenticatedSubmissionSettingsRouteImport.update({
    id: '/submission-settings',
    path: '/submission-settings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedScreeningQuarantineRoute =
  AuthenticatedScreeningQuarantineRouteImport.update({
    id: '/screening-quarantine',
    path: '/screening-quarantine',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedScreenerReviewSettingsRoute =
  AuthenticatedScreenerReviewSettingsRouteImport.update({
    id: '/screener-review-settings',
    path: '/screener-review-settings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedScreenerCapacityRoute =
  AuthenticatedScreenerCapacityRouteImport.update({
    id: '/screener-capacity',
    path: '/screener-capacity',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedScoreOutliersRoute =
  AuthenticatedScoreOutliersRouteImport.update({
    id: '/score-outliers',
    path: '/score-outliers',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMinerFeesRoute = AuthenticatedMinerFeesRouteImport.update({
  id: '/miner-fees',
  path: '/miner-fees',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInferenceRoutingRoute =
  AuthenticatedInferenceRoutingRouteImport.update({
    id: '/inference-routing',
    path: '/inference-routing',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInferenceConcurrencyRoute =
  AuthenticatedInferenceConcurrencyRouteImport.update({
    id: '/inference-concurrency',
    path: '/inference-concurrency',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCopyReviewRoute = AuthenticatedCopyReviewRouteImport.update({
  id: '/copy-review',
  path: '/copy-review',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedContinualRetestsRoute =
  AuthenticatedContinualRetestsRouteImport.update({
    id: '/continual-retests',
    path: '/continual-retests',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBenchmarkRolloutRoute =
  AuthenticatedBenchmarkRolloutRouteImport.update({
    id: '/benchmark-rollout',
    path: '/benchmark-rollout',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedArtifactReleaseRoute =
  AuthenticatedArtifactReleaseRouteImport.update({
    id: '/artifact-release',
    path: '/artifact-release',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedScreeningQuarantineIndexRoute =
  AuthenticatedScreeningQuarantineIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedScreeningQuarantineRoute,
  } as any)
const AuthenticatedScreeningQuarantineHistoryRoute =
  AuthenticatedScreeningQuarantineHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => AuthenticatedScreeningQuarantineRoute,
  } as any)
const AuthenticatedScreeningQuarantineDisputesRoute =
  AuthenticatedScreeningQuarantineDisputesRouteImport.update({
    id: '/disputes',
    path: '/disputes',
    getParentRoute: () => AuthenticatedScreeningQuarantineRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/artifact-release': typeof AuthenticatedArtifactReleaseRoute
  '/benchmark-rollout': typeof AuthenticatedBenchmarkRolloutRoute
  '/continual-retests': typeof AuthenticatedContinualRetestsRoute
  '/copy-review': typeof AuthenticatedCopyReviewRoute
  '/inference-concurrency': typeof AuthenticatedInferenceConcurrencyRoute
  '/inference-routing': typeof AuthenticatedInferenceRoutingRoute
  '/miner-fees': typeof AuthenticatedMinerFeesRoute
  '/score-outliers': typeof AuthenticatedScoreOutliersRoute
  '/screener-capacity': typeof AuthenticatedScreenerCapacityRoute
  '/screener-review-settings': typeof AuthenticatedScreenerReviewSettingsRoute
  '/screening-quarantine': typeof AuthenticatedScreeningQuarantineRouteWithChildren
  '/submission-settings': typeof AuthenticatedSubmissionSettingsRoute
  '/validator-slots': typeof AuthenticatedValidatorSlotsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/screening-quarantine/disputes': typeof AuthenticatedScreeningQuarantineDisputesRoute
  '/screening-quarantine/history': typeof AuthenticatedScreeningQuarantineHistoryRoute
  '/screening-quarantine/': typeof AuthenticatedScreeningQuarantineIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/artifact-release': typeof AuthenticatedArtifactReleaseRoute
  '/benchmark-rollout': typeof AuthenticatedBenchmarkRolloutRoute
  '/continual-retests': typeof AuthenticatedContinualRetestsRoute
  '/copy-review': typeof AuthenticatedCopyReviewRoute
  '/inference-concurrency': typeof AuthenticatedInferenceConcurrencyRoute
  '/inference-routing': typeof AuthenticatedInferenceRoutingRoute
  '/miner-fees': typeof AuthenticatedMinerFeesRoute
  '/score-outliers': typeof AuthenticatedScoreOutliersRoute
  '/screener-capacity': typeof AuthenticatedScreenerCapacityRoute
  '/screener-review-settings': typeof AuthenticatedScreenerReviewSettingsRoute
  '/submission-settings': typeof AuthenticatedSubmissionSettingsRoute
  '/validator-slots': typeof AuthenticatedValidatorSlotsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/screening-quarantine/disputes': typeof AuthenticatedScreeningQuarantineDisputesRoute
  '/screening-quarantine/history': typeof AuthenticatedScreeningQuarantineHistoryRoute
  '/screening-quarantine': typeof AuthenticatedScreeningQuarantineIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/artifact-release': typeof AuthenticatedArtifactReleaseRoute
  '/_authenticated/benchmark-rollout': typeof AuthenticatedBenchmarkRolloutRoute
  '/_authenticated/continual-retests': typeof AuthenticatedContinualRetestsRoute
  '/_authenticated/copy-review': typeof AuthenticatedCopyReviewRoute
  '/_authenticated/inference-concurrency': typeof AuthenticatedInferenceConcurrencyRoute
  '/_authenticated/inference-routing': typeof AuthenticatedInferenceRoutingRoute
  '/_authenticated/miner-fees': typeof AuthenticatedMinerFeesRoute
  '/_authenticated/score-outliers': typeof AuthenticatedScoreOutliersRoute
  '/_authenticated/screener-capacity': typeof AuthenticatedScreenerCapacityRoute
  '/_authenticated/screener-review-settings': typeof AuthenticatedScreenerReviewSettingsRoute
  '/_authenticated/screening-quarantine': typeof AuthenticatedScreeningQuarantineRouteWithChildren
  '/_authenticated/submission-settings': typeof AuthenticatedSubmissionSettingsRoute
  '/_authenticated/validator-slots': typeof AuthenticatedValidatorSlotsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_authenticated/screening-quarantine/disputes': typeof AuthenticatedScreeningQuarantineDisputesRoute
  '/_authenticated/screening-quarantine/history': typeof AuthenticatedScreeningQuarantineHistoryRoute
  '/_authenticated/screening-quarantine/': typeof AuthenticatedScreeningQuarantineIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/artifact-release'
    | '/benchmark-rollout'
    | '/continual-retests'
    | '/copy-review'
    | '/inference-concurrency'
    | '/inference-routing'
    | '/miner-fees'
    | '/score-outliers'
    | '/screener-capacity'
    | '/screener-review-settings'
    | '/screening-quarantine'
    | '/submission-settings'
    | '/validator-slots'
    | '/auth/callback'
    | '/screening-quarantine/disputes'
    | '/screening-quarantine/history'
    | '/screening-quarantine/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/artifact-release'
    | '/benchmark-rollout'
    | '/continual-retests'
    | '/copy-review'
    | '/inference-concurrency'
    | '/inference-routing'
    | '/miner-fees'
    | '/score-outliers'
    | '/screener-capacity'
    | '/screener-review-settings'
    | '/submission-settings'
    | '/validator-slots'
    | '/auth/callback'
    | '/screening-quarantine/disputes'
    | '/screening-quarantine/history'
    | '/screening-quarantine'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/artifact-release'
    | '/_authenticated/benchmark-rollout'
    | '/_authenticated/continual-retests'
    | '/_authenticated/copy-review'
    | '/_authenticated/inference-concurrency'
    | '/_authenticated/inference-routing'
    | '/_authenticated/miner-fees'
    | '/_authenticated/score-outliers'
    | '/_authenticated/screener-capacity'
    | '/_authenticated/screener-review-settings'
    | '/_authenticated/screening-quarantine'
    | '/_authenticated/submission-settings'
    | '/_authenticated/validator-slots'
    | '/auth/callback'
    | '/_authenticated/screening-quarantine/disputes'
    | '/_authenticated/screening-quarantine/history'
    | '/_authenticated/screening-quarantine/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/validator-slots': {
      id: '/_authenticated/validator-slots'
      path: '/validator-slots'
      fullPath: '/validator-slots'
      preLoaderRoute: typeof AuthenticatedValidatorSlotsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/submission-settings': {
      id: '/_authenticated/submission-settings'
      path: '/submission-settings'
      fullPath: '/submission-settings'
      preLoaderRoute: typeof AuthenticatedSubmissionSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/screening-quarantine': {
      id: '/_authenticated/screening-quarantine'
      path: '/screening-quarantine'
      fullPath: '/screening-quarantine'
      preLoaderRoute: typeof AuthenticatedScreeningQuarantineRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/screener-review-settings': {
      id: '/_authenticated/screener-review-settings'
      path: '/screener-review-settings'
      fullPath: '/screener-review-settings'
      preLoaderRoute: typeof AuthenticatedScreenerReviewSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/screener-capacity': {
      id: '/_authenticated/screener-capacity'
      path: '/screener-capacity'
      fullPath: '/screener-capacity'
      preLoaderRoute: typeof AuthenticatedScreenerCapacityRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/score-outliers': {
      id: '/_authenticated/score-outliers'
      path: '/score-outliers'
      fullPath: '/score-outliers'
      preLoaderRoute: typeof AuthenticatedScoreOutliersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/miner-fees': {
      id: '/_authenticated/miner-fees'
      path: '/miner-fees'
      fullPath: '/miner-fees'
      preLoaderRoute: typeof AuthenticatedMinerFeesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inference-routing': {
      id: '/_authenticated/inference-routing'
      path: '/inference-routing'
      fullPath: '/inference-routing'
      preLoaderRoute: typeof AuthenticatedInferenceRoutingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inference-concurrency': {
      id: '/_authenticated/inference-concurrency'
      path: '/inference-concurrency'
      fullPath: '/inference-concurrency'
      preLoaderRoute: typeof AuthenticatedInferenceConcurrencyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/copy-review': {
      id: '/_authenticated/copy-review'
      path: '/copy-review'
      fullPath: '/copy-review'
      preLoaderRoute: typeof AuthenticatedCopyReviewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/continual-retests': {
      id: '/_authenticated/continual-retests'
      path: '/continual-retests'
      fullPath: '/continual-retests'
      preLoaderRoute: typeof AuthenticatedContinualRetestsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/benchmark-rollout': {
      id: '/_authenticated/benchmark-rollout'
      path: '/benchmark-rollout'
      fullPath: '/benchmark-rollout'
      preLoaderRoute: typeof AuthenticatedBenchmarkRolloutRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/artifact-release': {
      id: '/_authenticated/artifact-release'
      path: '/artifact-release'
      fullPath: '/artifact-release'
      preLoaderRoute: typeof AuthenticatedArtifactReleaseRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/screening-quarantine/': {
      id: '/_authenticated/screening-quarantine/'
      path: '/'
      fullPath: '/screening-quarantine/'
      preLoaderRoute: typeof AuthenticatedScreeningQuarantineIndexRouteImport
      parentRoute: typeof AuthenticatedScreeningQuarantineRoute
    }
    '/_authenticated/screening-quarantine/history': {
      id: '/_authenticated/screening-quarantine/history'
      path: '/history'
      fullPath: '/screening-quarantine/history'
      preLoaderRoute: typeof AuthenticatedScreeningQuarantineHistoryRouteImport
      parentRoute: typeof AuthenticatedScreeningQuarantineRoute
    }
    '/_authenticated/screening-quarantine/disputes': {
      id: '/_authenticated/screening-quarantine/disputes'
      path: '/disputes'
      fullPath: '/screening-quarantine/disputes'
      preLoaderRoute: typeof AuthenticatedScreeningQuarantineDisputesRouteImport
      parentRoute: typeof AuthenticatedScreeningQuarantineRoute
    }
  }
}

interface AuthenticatedScreeningQuarantineRouteChildren {
  AuthenticatedScreeningQuarantineDisputesRoute: typeof AuthenticatedScreeningQuarantineDisputesRoute
  AuthenticatedScreeningQuarantineHistoryRoute: typeof AuthenticatedScreeningQuarantineHistoryRoute
  AuthenticatedScreeningQuarantineIndexRoute: typeof AuthenticatedScreeningQuarantineIndexRoute
}

const AuthenticatedScreeningQuarantineRouteChildren: AuthenticatedScreeningQuarantineRouteChildren =
  {
    AuthenticatedScreeningQuarantineDisputesRoute:
      AuthenticatedScreeningQuarantineDisputesRoute,
    AuthenticatedScreeningQuarantineHistoryRoute:
      AuthenticatedScreeningQuarantineHistoryRoute,
    AuthenticatedScreeningQuarantineIndexRoute:
      AuthenticatedScreeningQuarantineIndexRoute,
  }

const AuthenticatedScreeningQuarantineRouteWithChildren =
  AuthenticatedScreeningQuarantineRoute._addFileChildren(
    AuthenticatedScreeningQuarantineRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedArtifactReleaseRoute: typeof AuthenticatedArtifactReleaseRoute
  AuthenticatedBenchmarkRolloutRoute: typeof AuthenticatedBenchmarkRolloutRoute
  AuthenticatedContinualRetestsRoute: typeof AuthenticatedContinualRetestsRoute
  AuthenticatedCopyReviewRoute: typeof AuthenticatedCopyReviewRoute
  AuthenticatedInferenceConcurrencyRoute: typeof AuthenticatedInferenceConcurrencyRoute
  AuthenticatedInferenceRoutingRoute: typeof AuthenticatedInferenceRoutingRoute
  AuthenticatedMinerFeesRoute: typeof AuthenticatedMinerFeesRoute
  AuthenticatedScoreOutliersRoute: typeof AuthenticatedScoreOutliersRoute
  AuthenticatedScreenerCapacityRoute: typeof AuthenticatedScreenerCapacityRoute
  AuthenticatedScreenerReviewSettingsRoute: typeof AuthenticatedScreenerReviewSettingsRoute
  AuthenticatedScreeningQuarantineRoute: typeof AuthenticatedScreeningQuarantineRouteWithChildren
  AuthenticatedSubmissionSettingsRoute: typeof AuthenticatedSubmissionSettingsRoute
  AuthenticatedValidatorSlotsRoute: typeof AuthenticatedValidatorSlotsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedArtifactReleaseRoute: AuthenticatedArtifactReleaseRoute,
  AuthenticatedBenchmarkRolloutRoute: AuthenticatedBenchmarkRolloutRoute,
  AuthenticatedContinualRetestsRoute: AuthenticatedContinualRetestsRoute,
  AuthenticatedCopyReviewRoute: AuthenticatedCopyReviewRoute,
  AuthenticatedInferenceConcurrencyRoute:
    AuthenticatedInferenceConcurrencyRoute,
  AuthenticatedInferenceRoutingRoute: AuthenticatedInferenceRoutingRoute,
  AuthenticatedMinerFeesRoute: AuthenticatedMinerFeesRoute,
  AuthenticatedScoreOutliersRoute: AuthenticatedScoreOutliersRoute,
  AuthenticatedScreenerCapacityRoute: AuthenticatedScreenerCapacityRoute,
  AuthenticatedScreenerReviewSettingsRoute:
    AuthenticatedScreenerReviewSettingsRoute,
  AuthenticatedScreeningQuarantineRoute:
    AuthenticatedScreeningQuarantineRouteWithChildren,
  AuthenticatedSubmissionSettingsRoute: AuthenticatedSubmissionSettingsRoute,
  AuthenticatedValidatorSlotsRoute: AuthenticatedValidatorSlotsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
