package universe

// AccentColors returns the closed accent-colour pool the world draws the
// user's Ditto accent from. It is exposed for the generator-inverse adversary
// (cmd/parserprobe), which resolves a misspelled "twal-ish" request against the
// same public pool a product-quality harness would consult; exporting it
// changes no generated bytes.
func AccentColors() []string { return append([]string(nil), colors...) }
