#!/usr/bin/env bash
# Regenerate harness/go-template-baseline/BASELINE.md.
#
# Usage: scripts/render-baseline.sh <output-dir> <baseline-md-path>
#
# Steps:
#   1. Compute a SHA-256 over the concatenated public fixture JSONL files
#      and the response_quality/golden file. This is the "manifest hash"
#      contributors pin against.
#   2. Run the validator binary against the in-process echo-harness over
#      the public split for both mechanisms.
#   3. Parse the per-mechanism aggregates from the resulting weight
#      reports and rewrite BASELINE.md.
#
# The echo-harness is a placeholder; once the baseline image is
# published the CI release job replaces "echo-harness" with the real
# baseline-harness via docker. The structure of BASELINE.md is the
# same in both cases.
set -euo pipefail

OUT_DIR="${1:?output dir is required}"
BASELINE_MD="${2:?baseline.md path is required}"

ROOT="$(git rev-parse --show-toplevel)"
cd "$ROOT"

MANIFEST_HASH=$(find ditto/bench/fixtures -name '*.jsonl' -o -name '*.json' \
  | LC_ALL=C sort \
  | xargs cat \
  | sha256sum \
  | awk '{print $1}')

CORE_COUNT=$(find ditto/bench/fixtures/toolcall -name '*.jsonl' \
  | xargs -r grep -v -E '^\s*(//|#|$)' \
  | wc -l \
  | tr -d ' ')
RETR_COUNT=$(find ditto/bench/fixtures/retrieval -name '*.jsonl' \
  | xargs -r grep -v -E '^\s*(//|#|$)' \
  | wc -l \
  | tr -d ' ')

rm -rf "$OUT_DIR"
mkdir -p "$OUT_DIR"
DITTO_ECHO_HARNESS_BIN="$ROOT/bin/ditto-echo-harness" \
  "$ROOT/bin/ditto-validator" \
    --fixtures-root ditto/bench/fixtures \
    --secret baseline-bench \
    --self-test \
    --dry-run \
    --visibility public \
    --private-frac 0.0 \
    --canary-frac 0.0 \
    --deadline-ms 8000 \
    --budget-latency-ms 4000 \
    --report-dir "$OUT_DIR" \
    > "$OUT_DIR/validator.log" 2>&1

CORE_MEAN=$(python3 -c "
import json
import os
import sys
path = '$OUT_DIR/weights-ditto_core.json'
if not os.path.exists(path):
    print('n/a')
    sys.exit(0)
data = json.load(open(path))
means = [d.get('public_mean', 0.0) for d in data.get('details', [])]
print(f'{sum(means)/len(means):.3f}' if means else 'n/a')
")
RETR_MEAN=$(python3 -c "
import json
import os
import sys
path = '$OUT_DIR/weights-ditto_retrieval.json'
if not os.path.exists(path):
    print('n/a')
    sys.exit(0)
data = json.load(open(path))
means = [d.get('public_mean', 0.0) for d in data.get('details', [])]
print(f'{sum(means)/len(means):.3f}' if means else 'n/a')
")

cat > "$BASELINE_MD" <<EOF
# DittoBench reference baseline — latest score

This file is **regenerated by \`make baseline-bench\`**. Do not edit by hand;
edits will be overwritten on the next regeneration.

## Image

| Field          | Value                                                |
| -------------- | ---------------------------------------------------- |
| Image digest   | _(set by the CI release job that pushes the image)_  |
| Built from     | \`harness/go-template-baseline/Dockerfile\`            |
| Repo SHA       | $(git rev-parse HEAD)                               |

## Fixture corpus

| Field             | Value                                              |
| ----------------- | -------------------------------------------------- |
| Manifest hash     | \`$MANIFEST_HASH\` |
| Fixture root      | \`ditto/bench/fixtures\`                             |
| Core case count   | $CORE_COUNT                                        |
| Retrieval case count | $RETR_COUNT                                     |

## Score

Latency budgets used:

- \`--deadline-ms 8000\`
- \`--budget-latency-ms 4000\`

Anti-gaming knobs used:

- \`--private-frac 0.0\` (public-only run; no private/canary split applied)
- \`--canary-frac 0.0\`

| Mechanism         | Sample size | Mean score |
| ----------------- | ----------- | ---------- |
| \`ditto_core\`      | $CORE_COUNT | $CORE_MEAN |
| \`ditto_retrieval\` | $RETR_COUNT | $RETR_MEAN |

Miners should regenerate this file with their own harness via
\`make baseline-bench\` so a "beat the baseline by X%" claim is anchored
to the same fixture revision the baseline was scored against.
EOF

echo "baseline-bench: wrote $BASELINE_MD (manifest=$MANIFEST_HASH)"
