// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: concurrency_settings_queries.sql

package postgres

import (
	"context"
)

const getLatestInferenceConcurrencySettings = `-- name: GetLatestInferenceConcurrencySettings :one

SELECT revision, parent_revision, scope, settings, checksum, reason, actor, created_at FROM inference_concurrency_settings_revisions
WHERE scope = '*'
ORDER BY revision DESC
LIMIT 1
`

// Inference concurrency settings: an append-only revision board written by
// platform admin endpoints. The relay only ever reads the latest revision,
// on its OWN pooled connection, NEVER inside the admission transaction
// (doing so would extend the grant+ticket critical section), and caches it
// for 5 seconds in process. A DB error serves shipped defaults WITHOUT
// caching them; corrupt JSON payloads also fail open to shipped defaults.
// Latest whole-policy revision for the only scope ('*'). pgx.ErrNoRows means
// "no operator override yet": serve shipped defaults.
func (q *Queries) GetLatestInferenceConcurrencySettings(ctx context.Context) (InferenceConcurrencySettingsRevision, error) {
	row := q.db.QueryRow(ctx, getLatestInferenceConcurrencySettings)
	var i InferenceConcurrencySettingsRevision
	err := row.Scan(
		&i.Revision,
		&i.ParentRevision,
		&i.Scope,
		&i.Settings,
		&i.Checksum,
		&i.Reason,
		&i.Actor,
		&i.CreatedAt,
	)
	return i, err
}
