// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: confirmation_inference_queries.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const applyConfirmationGrantSettlement = `-- name: ApplyConfirmationGrantSettlement :one
UPDATE confirmation_inference_grants
SET active_requests = $1::integer,
    prompt_tokens = prompt_tokens + $2::bigint,
    completion_tokens = completion_tokens + $3::bigint,
    cost_microusd = cost_microusd + $4::bigint,
    updated_at = $5::timestamptz
WHERE grant_id = $6::uuid
RETURNING grant_id, ticket_id, bundle_id, validator_hotkey, lane, status, bearer_digest, broker_public_key, generation, model, provider, route_provider, receipt_provider, profile_revision, request_budget, token_budget, cost_budget_microusd, request_count, prompt_tokens, completion_tokens, cost_microusd, active_requests, expires_at, created_at, updated_at
`

type ApplyConfirmationGrantSettlementParams struct {
	ActiveRequests   int32              `json:"activeRequests"`
	PromptTokens     int64              `json:"promptTokens"`
	CompletionTokens int64              `json:"completionTokens"`
	CostMicrousd     int64              `json:"costMicrousd"`
	Now              pgtype.Timestamptz `json:"now"`
	GrantID          pgtype.UUID        `json:"grantId"`
}

// Settle-transaction grant accounting. active_requests is an ABSOLUTE value:
// the caller computes max(0, active_requests-1) from the locked row so the
// CHECK constraint never aborts the transaction. Spend columns are deltas.
// Returns the updated row so the caller can apply the exhaustion rule
// (request/token/cost budgets) without re-reading.
func (q *Queries) ApplyConfirmationGrantSettlement(ctx context.Context, arg ApplyConfirmationGrantSettlementParams) (ConfirmationInferenceGrant, error) {
	row := q.db.QueryRow(ctx, applyConfirmationGrantSettlement,
		arg.ActiveRequests,
		arg.PromptTokens,
		arg.CompletionTokens,
		arg.CostMicrousd,
		arg.Now,
		arg.GrantID,
	)
	var i ConfirmationInferenceGrant
	err := row.Scan(
		&i.GrantID,
		&i.TicketID,
		&i.BundleID,
		&i.ValidatorHotkey,
		&i.Lane,
		&i.Status,
		&i.BearerDigest,
		&i.BrokerPublicKey,
		&i.Generation,
		&i.Model,
		&i.Provider,
		&i.RouteProvider,
		&i.ReceiptProvider,
		&i.ProfileRevision,
		&i.RequestBudget,
		&i.TokenBudget,
		&i.CostBudgetMicrousd,
		&i.RequestCount,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.CostMicrousd,
		&i.ActiveRequests,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteConfirmationInferenceRequest = `-- name: DeleteConfirmationInferenceRequest :exec
DELETE FROM confirmation_inference_requests
WHERE grant_id = $1::uuid
  AND nonce = $2::uuid
`

type DeleteConfirmationInferenceRequestParams struct {
	GrantID pgtype.UUID `json:"grantId"`
	Nonce   pgtype.UUID `json:"nonce"`
}

// Decline cleanup for a just-inserted provisional row (budget/shape declines
// after the replay-guarding insert). Discarded by the endpoint's decline
// rollback; emitted for statement parity.
func (q *Queries) DeleteConfirmationInferenceRequest(ctx context.Context, arg DeleteConfirmationInferenceRequestParams) error {
	_, err := q.db.Exec(ctx, deleteConfirmationInferenceRequest, arg.GrantID, arg.Nonce)
	return err
}

const getConfirmationBundleTicketForUpdate = `-- name: GetConfirmationBundleTicketForUpdate :one
SELECT ticket_id, bundle_id, validator_hotkey, slot_id, status, attempt, issued_at, deadline, failure_reason, failed_at, created_at, failure_class, failure_stage, prepare_rejection, prepare_rejected_at FROM confirmation_bundle_tickets
WHERE ticket_id = $1::uuid
FOR UPDATE
`

// Rank-1 lock for confirmation admission. A missing ticket is legal; the
// liveness gate fails closed with LEASE_EXPIRED.
func (q *Queries) GetConfirmationBundleTicketForUpdate(ctx context.Context, ticketID pgtype.UUID) (ConfirmationBundleTicket, error) {
	row := q.db.QueryRow(ctx, getConfirmationBundleTicketForUpdate, ticketID)
	var i ConfirmationBundleTicket
	err := row.Scan(
		&i.TicketID,
		&i.BundleID,
		&i.ValidatorHotkey,
		&i.SlotID,
		&i.Status,
		&i.Attempt,
		&i.IssuedAt,
		&i.Deadline,
		&i.FailureReason,
		&i.FailedAt,
		&i.CreatedAt,
		&i.FailureClass,
		&i.FailureStage,
		&i.PrepareRejection,
		&i.PrepareRejectedAt,
	)
	return i, err
}

const getConfirmationInferenceGrant = `-- name: GetConfirmationInferenceGrant :one

SELECT grant_id, ticket_id, bundle_id, validator_hotkey, lane, status, bearer_digest, broker_public_key, generation, model, provider, route_provider, receipt_provider, profile_revision, request_budget, token_budget, cost_budget_microusd, request_count, prompt_tokens, completion_tokens, cost_microusd, active_requests, expires_at, created_at, updated_at FROM confirmation_inference_grants
WHERE grant_id = $1::uuid
`

// Confirmation inference: the purpose-bound ledger for one Bench v9
// confirmation ticket (ditto/db/queries/confirmation_inference.py).
// Confirmation deliberately has its own tables instead of weakening the hot
// ordinary inference_grants table with nullable foreign keys.
//
// Lock order mirrors the Python module exactly:
//
//	begin:  confirmation_bundle_tickets (rank 1, FOR UPDATE) ->
//	        confirmation_inference_grants (rank 2, FOR UPDATE) ->
//	        confirmation_inference_requests (rank 3, via the INSERT).
//	finish: confirmation_inference_grants (FOR UPDATE) ->
//	        confirmation_inference_requests (FOR UPDATE). No ticket lock.
//
// Unlocked snapshot by grant id: used to learn the owning ticket PK (so the
// ticket can be locked FIRST) and by the endpoints' pre-admission lane/proof
// gates. Never evaluate budget gates against this row.
func (q *Queries) GetConfirmationInferenceGrant(ctx context.Context, grantID pgtype.UUID) (ConfirmationInferenceGrant, error) {
	row := q.db.QueryRow(ctx, getConfirmationInferenceGrant, grantID)
	var i ConfirmationInferenceGrant
	err := row.Scan(
		&i.GrantID,
		&i.TicketID,
		&i.BundleID,
		&i.ValidatorHotkey,
		&i.Lane,
		&i.Status,
		&i.BearerDigest,
		&i.BrokerPublicKey,
		&i.Generation,
		&i.Model,
		&i.Provider,
		&i.RouteProvider,
		&i.ReceiptProvider,
		&i.ProfileRevision,
		&i.RequestBudget,
		&i.TokenBudget,
		&i.CostBudgetMicrousd,
		&i.RequestCount,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.CostMicrousd,
		&i.ActiveRequests,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getConfirmationInferenceGrantForUpdate = `-- name: GetConfirmationInferenceGrantForUpdate :one
SELECT grant_id, ticket_id, bundle_id, validator_hotkey, lane, status, bearer_digest, broker_public_key, generation, model, provider, route_provider, receipt_provider, profile_revision, request_budget, token_budget, cost_budget_microusd, request_count, prompt_tokens, completion_tokens, cost_microusd, active_requests, expires_at, created_at, updated_at FROM confirmation_inference_grants
WHERE grant_id = $1::uuid
FOR UPDATE
`

// Locked re-read (rank 2, after the ticket lock in begin; the first lock in
// finish). All gate evaluation uses ONLY the values this returns.
func (q *Queries) GetConfirmationInferenceGrantForUpdate(ctx context.Context, grantID pgtype.UUID) (ConfirmationInferenceGrant, error) {
	row := q.db.QueryRow(ctx, getConfirmationInferenceGrantForUpdate, grantID)
	var i ConfirmationInferenceGrant
	err := row.Scan(
		&i.GrantID,
		&i.TicketID,
		&i.BundleID,
		&i.ValidatorHotkey,
		&i.Lane,
		&i.Status,
		&i.BearerDigest,
		&i.BrokerPublicKey,
		&i.Generation,
		&i.Model,
		&i.Provider,
		&i.RouteProvider,
		&i.ReceiptProvider,
		&i.ProfileRevision,
		&i.RequestBudget,
		&i.TokenBudget,
		&i.CostBudgetMicrousd,
		&i.RequestCount,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.CostMicrousd,
		&i.ActiveRequests,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getConfirmationInferenceRequestForUpdate = `-- name: GetConfirmationInferenceRequestForUpdate :one
SELECT grant_id, nonce, generation, status, model, reserved_tokens, max_chargeable_tokens, prompt_tokens, completion_tokens, cost_microusd, upstream_provider, started_at, completed_at FROM confirmation_inference_requests
WHERE grant_id = $1::uuid
  AND nonce = $2::uuid
FOR UPDATE
`

type GetConfirmationInferenceRequestForUpdateParams struct {
	GrantID pgtype.UUID `json:"grantId"`
	Nonce   pgtype.UUID `json:"nonce"`
}

// Settle-path locked read (after the grant lock).
func (q *Queries) GetConfirmationInferenceRequestForUpdate(ctx context.Context, arg GetConfirmationInferenceRequestForUpdateParams) (ConfirmationInferenceRequest, error) {
	row := q.db.QueryRow(ctx, getConfirmationInferenceRequestForUpdate, arg.GrantID, arg.Nonce)
	var i ConfirmationInferenceRequest
	err := row.Scan(
		&i.GrantID,
		&i.Nonce,
		&i.Generation,
		&i.Status,
		&i.Model,
		&i.ReservedTokens,
		&i.MaxChargeableTokens,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.CostMicrousd,
		&i.UpstreamProvider,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const incrementConfirmationGrantAdmission = `-- name: IncrementConfirmationGrantAdmission :exec
UPDATE confirmation_inference_grants
SET request_count = request_count + 1,
    active_requests = active_requests + 1,
    updated_at = $1::timestamptz
WHERE grant_id = $2::uuid
`

type IncrementConfirmationGrantAdmissionParams struct {
	Now     pgtype.Timestamptz `json:"now"`
	GrantID pgtype.UUID        `json:"grantId"`
}

// Admission bookkeeping after the request row INSERT. Grant row is locked by
// the caller.
func (q *Queries) IncrementConfirmationGrantAdmission(ctx context.Context, arg IncrementConfirmationGrantAdmissionParams) error {
	_, err := q.db.Exec(ctx, incrementConfirmationGrantAdmission, arg.Now, arg.GrantID)
	return err
}

const insertConfirmationInferenceRequest = `-- name: InsertConfirmationInferenceRequest :one
INSERT INTO confirmation_inference_requests (
    grant_id,
    nonce,
    generation,
    status,
    model,
    reserved_tokens,
    max_chargeable_tokens,
    prompt_tokens,
    completion_tokens,
    cost_microusd,
    started_at
) VALUES (
    $1::uuid,
    $2::uuid,
    $3::integer,
    'started',
    $4::text,
    $5::bigint,
    $6::bigint,
    0,
    0,
    0,
    $7::timestamptz
)
ON CONFLICT (grant_id, nonce) DO NOTHING
RETURNING grant_id, nonce, generation, status, model, reserved_tokens, max_chargeable_tokens, prompt_tokens, completion_tokens, cost_microusd, upstream_provider, started_at, completed_at
`

type InsertConfirmationInferenceRequestParams struct {
	GrantID             pgtype.UUID        `json:"grantId"`
	Nonce               pgtype.UUID        `json:"nonce"`
	Generation          int32              `json:"generation"`
	Model               string             `json:"model"`
	ReservedTokens      int64              `json:"reservedTokens"`
	MaxChargeableTokens int64              `json:"maxChargeableTokens"`
	StartedAt           pgtype.Timestamptz `json:"startedAt"`
}

// Replay-safe admission INSERT (PR #712 semantics): ON CONFLICT DO NOTHING on
// the (grant_id, nonce) PK collapses replay detection into the insert itself —
// zero rows back (pgx.ErrNoRows under :one) means NONCE_REPLAYED, and the
// admission transaction is never poisoned, so no savepoint is needed.
// reserved_tokens/max_chargeable_tokens are pre-clamped by the caller
// (max(1, reservation) / max(1, reservation, ceiling)) so the provisional row
// stays constraint-valid and replay detection stays ahead of
// malformed-reservation classification; a malformed fresh request deletes the
// row again (DeleteConfirmationInferenceRequest).
func (q *Queries) InsertConfirmationInferenceRequest(ctx context.Context, arg InsertConfirmationInferenceRequestParams) (ConfirmationInferenceRequest, error) {
	row := q.db.QueryRow(ctx, insertConfirmationInferenceRequest,
		arg.GrantID,
		arg.Nonce,
		arg.Generation,
		arg.Model,
		arg.ReservedTokens,
		arg.MaxChargeableTokens,
		arg.StartedAt,
	)
	var i ConfirmationInferenceRequest
	err := row.Scan(
		&i.GrantID,
		&i.Nonce,
		&i.Generation,
		&i.Status,
		&i.Model,
		&i.ReservedTokens,
		&i.MaxChargeableTokens,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.CostMicrousd,
		&i.UpstreamProvider,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const markConfirmationInferenceGrantExhausted = `-- name: MarkConfirmationInferenceGrantExhausted :exec
UPDATE confirmation_inference_grants
SET status = 'exhausted',
    updated_at = $1::timestamptz
WHERE grant_id = $2::uuid
`

type MarkConfirmationInferenceGrantExhaustedParams struct {
	Now     pgtype.Timestamptz `json:"now"`
	GrantID pgtype.UUID        `json:"grantId"`
}

// Terminal budget exhaustion. The committed writer in relay practice is the
// settle transaction (finish_confirmation_inference_request).
func (q *Queries) MarkConfirmationInferenceGrantExhausted(ctx context.Context, arg MarkConfirmationInferenceGrantExhaustedParams) error {
	_, err := q.db.Exec(ctx, markConfirmationInferenceGrantExhausted, arg.Now, arg.GrantID)
	return err
}

const revokeConfirmationInferenceGrant = `-- name: RevokeConfirmationInferenceGrant :exec
UPDATE confirmation_inference_grants
SET status = 'revoked',
    updated_at = $1::timestamptz
WHERE grant_id = $2::uuid
`

type RevokeConfirmationInferenceGrantParams struct {
	Now     pgtype.Timestamptz `json:"now"`
	GrantID pgtype.UUID        `json:"grantId"`
}

// Liveness-gate revocation write. On the relay endpoints a decline rolls the
// admission transaction back, so this write is discarded there — emitted for
// statement parity with the Python module.
func (q *Queries) RevokeConfirmationInferenceGrant(ctx context.Context, arg RevokeConfirmationInferenceGrantParams) error {
	_, err := q.db.Exec(ctx, revokeConfirmationInferenceGrant, arg.Now, arg.GrantID)
	return err
}

const settleConfirmationInferenceRequest = `-- name: SettleConfirmationInferenceRequest :exec
UPDATE confirmation_inference_requests
SET status = $1::text,
    prompt_tokens = $2::bigint,
    completion_tokens = $3::bigint,
    cost_microusd = $4::bigint,
    upstream_provider = $5::text,
    completed_at = $6::timestamptz
WHERE grant_id = $7::uuid
  AND nonce = $8::uuid
`

type SettleConfirmationInferenceRequestParams struct {
	Status           string             `json:"status"`
	PromptTokens     int64              `json:"promptTokens"`
	CompletionTokens int64              `json:"completionTokens"`
	CostMicrousd     int64              `json:"costMicrousd"`
	UpstreamProvider pgtype.Text        `json:"upstreamProvider"`
	CompletedAt      pgtype.Timestamptz `json:"completedAt"`
	GrantID          pgtype.UUID        `json:"grantId"`
	Nonce            pgtype.UUID        `json:"nonce"`
}

// The settle write for a (locked) confirmation request row. The
// non-deliverable -> reservation-charged/failed rewrite is applied by the
// caller before this runs.
func (q *Queries) SettleConfirmationInferenceRequest(ctx context.Context, arg SettleConfirmationInferenceRequestParams) error {
	_, err := q.db.Exec(ctx, settleConfirmationInferenceRequest,
		arg.Status,
		arg.PromptTokens,
		arg.CompletionTokens,
		arg.CostMicrousd,
		arg.UpstreamProvider,
		arg.CompletedAt,
		arg.GrantID,
		arg.Nonce,
	)
	return err
}
