// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: inference_requests_queries.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelInferenceRequestChargingReservation = `-- name: CancelInferenceRequestChargingReservation :exec
UPDATE inference_requests
SET status = 'canceled',
    prompt_tokens = reserved_tokens,
    completed_at = $1::timestamptz
WHERE grant_id = $2::uuid
  AND nonce = $3::uuid
`

type CancelInferenceRequestChargingReservationParams struct {
	Now     pgtype.Timestamptz `json:"now"`
	GrantID pgtype.UUID        `json:"grantId"`
	Nonce   pgtype.UUID        `json:"nonce"`
}

// Reclamation write: cancel a (locked) started request and charge its full
// reservation as prompt tokens — the estimate, not the byte count (see
// test_a_reclaimed_request_is_charged_the_estimate_not_the_byte_count). The
// matching grant-side charge is AddReclaimedChatTokens /
// AddReclaimedEmbeddingTokens.
func (q *Queries) CancelInferenceRequestChargingReservation(ctx context.Context, arg CancelInferenceRequestChargingReservationParams) error {
	_, err := q.db.Exec(ctx, cancelInferenceRequestChargingReservation, arg.Now, arg.GrantID, arg.Nonce)
	return err
}

const countRecentGlobalRequests = `-- name: CountRecentGlobalRequests :one
SELECT COUNT(*)::bigint FROM inference_requests
WHERE request_kind = $1::text
  AND started_at >= $2::timestamptz
`

type CountRecentGlobalRequestsParams struct {
	RequestKind string             `json:"requestKind"`
	Since       pgtype.Timestamptz `json:"since"`
}

// Global RPM rail; same any-status window semantics.
func (q *Queries) CountRecentGlobalRequests(ctx context.Context, arg CountRecentGlobalRequestsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRecentGlobalRequests, arg.RequestKind, arg.Since)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countRecentGrantRequests = `-- name: CountRecentGrantRequests :one
SELECT COUNT(*)::bigint FROM inference_requests
WHERE grant_id = $1::uuid
  AND request_kind = $2::text
  AND started_at >= $3::timestamptz
`

type CountRecentGrantRequestsParams struct {
	GrantID     pgtype.UUID        `json:"grantId"`
	RequestKind string             `json:"requestKind"`
	Since       pgtype.Timestamptz `json:"since"`
}

// Per-ticket RPM rail: rows of ANY status count toward the minute window
// (finished requests still count — see
// test_ticket_request_rate_is_bounded_after_requests_finish). Unlocked,
// best-effort by design.
func (q *Queries) CountRecentGrantRequests(ctx context.Context, arg CountRecentGrantRequestsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRecentGrantRequests, arg.GrantID, arg.RequestKind, arg.Since)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countRecentValidatorRequests = `-- name: CountRecentValidatorRequests :one
SELECT COUNT(*)::bigint
FROM inference_requests r
JOIN inference_grants g ON g.grant_id = r.grant_id
WHERE g.validator_hotkey = $1::text
  AND r.request_kind = $2::text
  AND r.started_at >= $3::timestamptz
`

type CountRecentValidatorRequestsParams struct {
	ValidatorHotkey string             `json:"validatorHotkey"`
	RequestKind     string             `json:"requestKind"`
	Since           pgtype.Timestamptz `json:"since"`
}

// Per-validator RPM rail; same any-status window semantics.
func (q *Queries) CountRecentValidatorRequests(ctx context.Context, arg CountRecentValidatorRequestsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRecentValidatorRequests, arg.ValidatorHotkey, arg.RequestKind, arg.Since)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countStartedInferenceRequests = `-- name: CountStartedInferenceRequests :one
SELECT COUNT(*)::bigint FROM inference_requests
WHERE grant_id = $1::uuid
  AND status = 'started'
  AND request_kind = $2::text
`

type CountStartedInferenceRequestsParams struct {
	GrantID     pgtype.UUID `json:"grantId"`
	RequestKind string      `json:"requestKind"`
}

// Post-reclamation lane recount input (written back via
// SetGrant*ActiveRequests).
func (q *Queries) CountStartedInferenceRequests(ctx context.Context, arg CountStartedInferenceRequestsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countStartedInferenceRequests, arg.GrantID, arg.RequestKind)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getInferenceRequest = `-- name: GetInferenceRequest :one

SELECT grant_id, nonce, generation, status, model, reserved_tokens, prompt_tokens, completion_tokens, cost_microusd, started_at, completed_at, upstream_provider, timed_out, latency_ms, request_kind, upstream_attempts, max_chargeable_tokens, openrouter_attempts, fallback_phase, terminal_error_code FROM inference_requests
WHERE grant_id = $1::uuid
  AND nonce = $2::uuid
`

type GetInferenceRequestParams struct {
	GrantID pgtype.UUID `json:"grantId"`
	Nonce   pgtype.UUID `json:"nonce"`
}

// Inference requests: LOCK RANK 3 (locked only after ticket and grant). The
// (grant_id, nonce) composite PK is the distributed nonce-replay guard
// across relay replicas; InsertInferenceRequest MUST run inside a savepoint
// so a unique violation converts to NONCE_REPLAYED without poisoning the
// admission transaction.
// Fast (unlocked) replay check during admission.
func (q *Queries) GetInferenceRequest(ctx context.Context, arg GetInferenceRequestParams) (InferenceRequest, error) {
	row := q.db.QueryRow(ctx, getInferenceRequest, arg.GrantID, arg.Nonce)
	var i InferenceRequest
	err := row.Scan(
		&i.GrantID,
		&i.Nonce,
		&i.Generation,
		&i.Status,
		&i.Model,
		&i.ReservedTokens,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.CostMicrousd,
		&i.StartedAt,
		&i.CompletedAt,
		&i.UpstreamProvider,
		&i.TimedOut,
		&i.LatencyMs,
		&i.RequestKind,
		&i.UpstreamAttempts,
		&i.MaxChargeableTokens,
		&i.OpenrouterAttempts,
		&i.FallbackPhase,
		&i.TerminalErrorCode,
	)
	return i, err
}

const getInferenceRequestForUpdate = `-- name: GetInferenceRequestForUpdate :one
SELECT grant_id, nonce, generation, status, model, reserved_tokens, prompt_tokens, completion_tokens, cost_microusd, started_at, completed_at, upstream_provider, timed_out, latency_ms, request_kind, upstream_attempts, max_chargeable_tokens, openrouter_attempts, fallback_phase, terminal_error_code FROM inference_requests
WHERE grant_id = $1::uuid
  AND nonce = $2::uuid
FOR UPDATE
`

type GetInferenceRequestForUpdateParams struct {
	GrantID pgtype.UUID `json:"grantId"`
	Nonce   pgtype.UUID `json:"nonce"`
}

// Settle-path locked read (rank 3, after ticket and grant locks).
func (q *Queries) GetInferenceRequestForUpdate(ctx context.Context, arg GetInferenceRequestForUpdateParams) (InferenceRequest, error) {
	row := q.db.QueryRow(ctx, getInferenceRequestForUpdate, arg.GrantID, arg.Nonce)
	var i InferenceRequest
	err := row.Scan(
		&i.GrantID,
		&i.Nonce,
		&i.Generation,
		&i.Status,
		&i.Model,
		&i.ReservedTokens,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.CostMicrousd,
		&i.StartedAt,
		&i.CompletedAt,
		&i.UpstreamProvider,
		&i.TimedOut,
		&i.LatencyMs,
		&i.RequestKind,
		&i.UpstreamAttempts,
		&i.MaxChargeableTokens,
		&i.OpenrouterAttempts,
		&i.FallbackPhase,
		&i.TerminalErrorCode,
	)
	return i, err
}

const insertInferenceRequest = `-- name: InsertInferenceRequest :one
INSERT INTO inference_requests (
    grant_id,
    nonce,
    generation,
    status,
    request_kind,
    model,
    reserved_tokens,
    max_chargeable_tokens,
    prompt_tokens,
    completion_tokens,
    cost_microusd,
    started_at
) VALUES (
    $1::uuid,
    $2::uuid,
    $3::integer,
    'started',
    $4::text,
    $5::text,
    $6::bigint,
    $7::bigint,
    0,
    0,
    0,
    $8::timestamptz
)
RETURNING grant_id, nonce, generation, status, model, reserved_tokens, prompt_tokens, completion_tokens, cost_microusd, started_at, completed_at, upstream_provider, timed_out, latency_ms, request_kind, upstream_attempts, max_chargeable_tokens, openrouter_attempts, fallback_phase, terminal_error_code
`

type InsertInferenceRequestParams struct {
	GrantID             pgtype.UUID        `json:"grantId"`
	Nonce               pgtype.UUID        `json:"nonce"`
	Generation          int32              `json:"generation"`
	RequestKind         string             `json:"requestKind"`
	Model               string             `json:"model"`
	ReservedTokens      int64              `json:"reservedTokens"`
	MaxChargeableTokens int64              `json:"maxChargeableTokens"`
	StartedAt           pgtype.Timestamptz `json:"startedAt"`
}

// The admission INSERT (run inside a savepoint; PK violation =>
// NONCE_REPLAYED). generation comes from the LOCKED grant row;
// max_chargeable_tokens is max(token_reservation, byte-derived ceiling),
// computed by the caller.
func (q *Queries) InsertInferenceRequest(ctx context.Context, arg InsertInferenceRequestParams) (InferenceRequest, error) {
	row := q.db.QueryRow(ctx, insertInferenceRequest,
		arg.GrantID,
		arg.Nonce,
		arg.Generation,
		arg.RequestKind,
		arg.Model,
		arg.ReservedTokens,
		arg.MaxChargeableTokens,
		arg.StartedAt,
	)
	var i InferenceRequest
	err := row.Scan(
		&i.GrantID,
		&i.Nonce,
		&i.Generation,
		&i.Status,
		&i.Model,
		&i.ReservedTokens,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.CostMicrousd,
		&i.StartedAt,
		&i.CompletedAt,
		&i.UpstreamProvider,
		&i.TimedOut,
		&i.LatencyMs,
		&i.RequestKind,
		&i.UpstreamAttempts,
		&i.MaxChargeableTokens,
		&i.OpenrouterAttempts,
		&i.FallbackPhase,
		&i.TerminalErrorCode,
	)
	return i, err
}

const listStaleStartedInferenceRequestsForUpdate = `-- name: ListStaleStartedInferenceRequestsForUpdate :many
SELECT grant_id, nonce, generation, status, model, reserved_tokens, prompt_tokens, completion_tokens, cost_microusd, started_at, completed_at, upstream_provider, timed_out, latency_ms, request_kind, upstream_attempts, max_chargeable_tokens, openrouter_attempts, fallback_phase, terminal_error_code FROM inference_requests
WHERE grant_id = $1::uuid
  AND status = 'started'
  AND request_kind = $2::text
  AND started_at < $3::timestamptz
ORDER BY nonce
FOR UPDATE
`

type ListStaleStartedInferenceRequestsForUpdateParams struct {
	GrantID     pgtype.UUID        `json:"grantId"`
	RequestKind string             `json:"requestKind"`
	Cutoff      pgtype.Timestamptz `json:"cutoff"`
}

// Admission stale reclamation: started requests of this grant+lane older
// than the recovery window (started_at < now - 2*timeout_seconds; the caller
// computes the cutoff). Locked at rank 3.
func (q *Queries) ListStaleStartedInferenceRequestsForUpdate(ctx context.Context, arg ListStaleStartedInferenceRequestsForUpdateParams) ([]InferenceRequest, error) {
	rows, err := q.db.Query(ctx, listStaleStartedInferenceRequestsForUpdate, arg.GrantID, arg.RequestKind, arg.Cutoff)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InferenceRequest
	for rows.Next() {
		var i InferenceRequest
		if err := rows.Scan(
			&i.GrantID,
			&i.Nonce,
			&i.Generation,
			&i.Status,
			&i.Model,
			&i.ReservedTokens,
			&i.PromptTokens,
			&i.CompletionTokens,
			&i.CostMicrousd,
			&i.StartedAt,
			&i.CompletedAt,
			&i.UpstreamProvider,
			&i.TimedOut,
			&i.LatencyMs,
			&i.RequestKind,
			&i.UpstreamAttempts,
			&i.MaxChargeableTokens,
			&i.OpenrouterAttempts,
			&i.FallbackPhase,
			&i.TerminalErrorCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStartedInferenceRequestsForUpdate = `-- name: ListStartedInferenceRequestsForUpdate :many
SELECT grant_id, nonce, generation, status, model, reserved_tokens, prompt_tokens, completion_tokens, cost_microusd, started_at, completed_at, upstream_provider, timed_out, latency_ms, request_kind, upstream_attempts, max_chargeable_tokens, openrouter_attempts, fallback_phase, terminal_error_code FROM inference_requests
WHERE grant_id = $1::uuid
  AND status = 'started'
ORDER BY nonce
FOR UPDATE
`

// /exchange rotation gate: every started request for the grant, locked.
// Ordered by nonce for a deterministic lock order within rank 3 (mirrors
// revoke_ticket_inference's ORDER BY grant_id, nonce).
func (q *Queries) ListStartedInferenceRequestsForUpdate(ctx context.Context, grantID pgtype.UUID) ([]InferenceRequest, error) {
	rows, err := q.db.Query(ctx, listStartedInferenceRequestsForUpdate, grantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InferenceRequest
	for rows.Next() {
		var i InferenceRequest
		if err := rows.Scan(
			&i.GrantID,
			&i.Nonce,
			&i.Generation,
			&i.Status,
			&i.Model,
			&i.ReservedTokens,
			&i.PromptTokens,
			&i.CompletionTokens,
			&i.CostMicrousd,
			&i.StartedAt,
			&i.CompletedAt,
			&i.UpstreamProvider,
			&i.TimedOut,
			&i.LatencyMs,
			&i.RequestKind,
			&i.UpstreamAttempts,
			&i.MaxChargeableTokens,
			&i.OpenrouterAttempts,
			&i.FallbackPhase,
			&i.TerminalErrorCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const settleInferenceRequest = `-- name: SettleInferenceRequest :exec
UPDATE inference_requests
SET status = $1::text,
    prompt_tokens = $2::bigint,
    completion_tokens = $3::bigint,
    cost_microusd = $4::bigint,
    upstream_provider = $5::text,
    upstream_attempts = $6::integer,
    openrouter_attempts = $7::integer,
    fallback_phase = $8::integer,
    terminal_error_code = $9::text,
    timed_out = $10::boolean,
    latency_ms = $11::integer,
    completed_at = $12::timestamptz
WHERE grant_id = $13::uuid
  AND nonce = $14::uuid
`

type SettleInferenceRequestParams struct {
	Status             string             `json:"status"`
	PromptTokens       int64              `json:"promptTokens"`
	CompletionTokens   int64              `json:"completionTokens"`
	CostMicrousd       int64              `json:"costMicrousd"`
	UpstreamProvider   pgtype.Text        `json:"upstreamProvider"`
	UpstreamAttempts   int32              `json:"upstreamAttempts"`
	OpenrouterAttempts int32              `json:"openrouterAttempts"`
	FallbackPhase      int32              `json:"fallbackPhase"`
	TerminalErrorCode  pgtype.Text        `json:"terminalErrorCode"`
	TimedOut           bool               `json:"timedOut"`
	LatencyMs          pgtype.Int4        `json:"latencyMs"`
	CompletedAt        pgtype.Timestamptz `json:"completedAt"`
	GrantID            pgtype.UUID        `json:"grantId"`
	Nonce              pgtype.UUID        `json:"nonce"`
}

// The settle write for a (locked) request row. All clamps (non-negative
// attempts, fallback_phase in {0,1}, token/ceiling clamping, the
// completed-but-not-deliverable -> 'canceled' status rule) are applied by
// the caller before this runs, so the DB CHECK constraints never abort the
// settle transaction.
func (q *Queries) SettleInferenceRequest(ctx context.Context, arg SettleInferenceRequestParams) error {
	_, err := q.db.Exec(ctx, settleInferenceRequest,
		arg.Status,
		arg.PromptTokens,
		arg.CompletionTokens,
		arg.CostMicrousd,
		arg.UpstreamProvider,
		arg.UpstreamAttempts,
		arg.OpenrouterAttempts,
		arg.FallbackPhase,
		arg.TerminalErrorCode,
		arg.TimedOut,
		arg.LatencyMs,
		arg.CompletedAt,
		arg.GrantID,
		arg.Nonce,
	)
	return err
}

const sumStartedReservedTokens = `-- name: SumStartedReservedTokens :one
SELECT COALESCE(SUM(reserved_tokens), 0)::bigint FROM inference_requests
WHERE grant_id = $1::uuid
  AND status = 'started'
  AND request_kind = $2::text
`

type SumStartedReservedTokensParams struct {
	GrantID     pgtype.UUID `json:"grantId"`
	RequestKind string      `json:"requestKind"`
}

// Token-headroom gate input: unlocked aggregate of in-flight reservations
// for this grant+lane.
func (q *Queries) SumStartedReservedTokens(ctx context.Context, arg SumStartedReservedTokensParams) (int64, error) {
	row := q.db.QueryRow(ctx, sumStartedReservedTokens, arg.GrantID, arg.RequestKind)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}
