// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: inference_routes_queries.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getInferenceRoutingPolicy = `-- name: GetInferenceRoutingPolicy :one

SELECT model, revision, enabled, speed_weight, cost_weight, exploration_weight, exploration_ticket_budget, min_tool_accuracy, min_composite, min_calibration_samples, max_error_rate, max_timeout_rate, cooldown_seconds, ewma_alpha, updated_at FROM inference_routing_policies
WHERE model = $1::text
`

// Provider routes and routing policies. Route rows sit OUTSIDE the
// ticket->grant->request lock chain and are only ever locked singly, after
// the hot three, inside the chat settle transaction
// (record_route_observation). The relay never writes
// inference_routing_policies (platform admin owns them) and never touches
// routes on the embedding lane.
// Unlocked policy read (EWMA alpha, cooldown). Missing row => observation
// no-op.
func (q *Queries) GetInferenceRoutingPolicy(ctx context.Context, model string) (InferenceRoutingPolicy, error) {
	row := q.db.QueryRow(ctx, getInferenceRoutingPolicy, model)
	var i InferenceRoutingPolicy
	err := row.Scan(
		&i.Model,
		&i.Revision,
		&i.Enabled,
		&i.SpeedWeight,
		&i.CostWeight,
		&i.ExplorationWeight,
		&i.ExplorationTicketBudget,
		&i.MinToolAccuracy,
		&i.MinComposite,
		&i.MinCalibrationSamples,
		&i.MaxErrorRate,
		&i.MaxTimeoutRate,
		&i.CooldownSeconds,
		&i.EwmaAlpha,
		&i.UpdatedAt,
	)
	return i, err
}

const observeInferenceProviderRoute = `-- name: ObserveInferenceProviderRoute :execrows
UPDATE inference_provider_routes AS r
SET sample_count = r.sample_count + 1,
    ewma_latency_ms = CASE
        WHEN r.ewma_latency_ms IS NULL THEN $1::double precision
        ELSE p.ewma_alpha * $1::double precision
             + (1 - p.ewma_alpha) * r.ewma_latency_ms
    END,
    ewma_tokens_per_second = CASE
        WHEN NOT $2::boolean THEN r.ewma_tokens_per_second
        WHEN r.ewma_tokens_per_second IS NULL THEN $3::double precision
        ELSE p.ewma_alpha * $3::double precision
             + (1 - p.ewma_alpha) * r.ewma_tokens_per_second
    END,
    ewma_error_rate = p.ewma_alpha * $4::double precision
        + (1 - p.ewma_alpha) * r.ewma_error_rate,
    ewma_timeout_rate = p.ewma_alpha * $5::double precision
        + (1 - p.ewma_alpha) * r.ewma_timeout_rate,
    ewma_cost_microusd = CASE
        WHEN NOT $6::boolean THEN r.ewma_cost_microusd
        WHEN r.ewma_cost_microusd IS NULL THEN $7::double precision
        ELSE p.ewma_alpha * $7::double precision
             + (1 - p.ewma_alpha) * r.ewma_cost_microusd
    END,
    status = CASE WHEN $8::boolean THEN 'healthy' ELSE 'degraded' END,
    cooldown_until = CASE
        WHEN $8::boolean THEN NULL
        ELSE $9::timestamptz + make_interval(secs => p.cooldown_seconds)
    END,
    last_observed_at = $9::timestamptz,
    updated_at = $9::timestamptz
FROM inference_routing_policies AS p
WHERE r.model = $10::text
  AND r.provider = $11::text
  AND r.profile_revision = $12::text
  AND p.model = r.model
`

type ObserveInferenceProviderRouteParams struct {
	LatencyMs               float64            `json:"latencyMs"`
	TokensPerSecondObserved bool               `json:"tokensPerSecondObserved"`
	TokensPerSecond         float64            `json:"tokensPerSecond"`
	ErrorObserved           float64            `json:"errorObserved"`
	TimeoutObserved         float64            `json:"timeoutObserved"`
	CostObserved            bool               `json:"costObserved"`
	CostMicrousd            float64            `json:"costMicrousd"`
	Success                 bool               `json:"success"`
	Now                     pgtype.Timestamptz `json:"now"`
	Model                   string             `json:"model"`
	Provider                string             `json:"provider"`
	ProfileRevision         string             `json:"profileRevision"`
}

// Fold one chat-settle observation into the route row in a single statement.
// Before 2026-09-08 this was SELECT ... FOR UPDATE, a policy read, EWMA math
// in Go, then an UPDATE: every chat settle on the subnet took the same one of
// ~22 route rows exclusively across three round trips while still holding
// its ticket->grant->request locks, so route contention (1.2 s average
// waits) inflated every rail behind it. The EWMA folds, healthy/degraded
// status, and cooldown are computed here from the current row and the
// model's routing policy under the UPDATE's own brief row lock. A missing
// route or policy row updates nothing (0 rows), matching the old no-op.
//
//	ewma(prev, x) = alpha*x + (1-alpha)*prev, seeded with x when prev is NULL.
func (q *Queries) ObserveInferenceProviderRoute(ctx context.Context, arg ObserveInferenceProviderRouteParams) (int64, error) {
	result, err := q.db.Exec(ctx, observeInferenceProviderRoute,
		arg.LatencyMs,
		arg.TokensPerSecondObserved,
		arg.TokensPerSecond,
		arg.ErrorObserved,
		arg.TimeoutObserved,
		arg.CostObserved,
		arg.CostMicrousd,
		arg.Success,
		arg.Now,
		arg.Model,
		arg.Provider,
		arg.ProfileRevision,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
