// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: inference_grants_queries.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activateInferenceGrant = `-- name: ActivateInferenceGrant :exec
UPDATE inference_grants
SET bearer_digest = $1::text,
    broker_public_key = $2::text,
    generation = generation + 1,
    status = 'active',
    slot_id = $3::text,
    expires_at = $4::timestamptz,
    active_requests = 0,
    embedding_active_requests = 0,
    updated_at = $5::timestamptz
WHERE grant_id = $6::uuid
`

type ActivateInferenceGrantParams struct {
	BearerDigest    string             `json:"bearerDigest"`
	BrokerPublicKey string             `json:"brokerPublicKey"`
	SlotID          string             `json:"slotId"`
	ExpiresAt       pgtype.Timestamptz `json:"expiresAt"`
	Now             pgtype.Timestamptz `json:"now"`
	GrantID         pgtype.UUID        `json:"grantId"`
}

// The /exchange rotation write: store the bearer digest (hex sha256 of the
// opaque bearer, which is returned once and never stored in clear), the
// broker public key (base64url with trailing '=' stripped by the caller),
// bump the generation, adopt the ticket's slot and deadline, and zero both
// lane active counters. Runs only after the caller validated the grant
// against the LOCKED ticket and grant rows.
func (q *Queries) ActivateInferenceGrant(ctx context.Context, arg ActivateInferenceGrantParams) error {
	_, err := q.db.Exec(ctx, activateInferenceGrant,
		arg.BearerDigest,
		arg.BrokerPublicKey,
		arg.SlotID,
		arg.ExpiresAt,
		arg.Now,
		arg.GrantID,
	)
	return err
}

const addReclaimedChatTokens = `-- name: AddReclaimedChatTokens :exec
UPDATE inference_grants
SET prompt_tokens = prompt_tokens + $1::bigint,
    updated_at = $2::timestamptz
WHERE grant_id = $3::uuid
`

type AddReclaimedChatTokensParams struct {
	ReservedTokens int64              `json:"reservedTokens"`
	Now            pgtype.Timestamptz `json:"now"`
	GrantID        pgtype.UUID        `json:"grantId"`
}

// Stale-reclamation charge: a canceled in-flight chat request is charged its
// full reservation into the grant's prompt_tokens. Grant row is locked by
// the caller.
func (q *Queries) AddReclaimedChatTokens(ctx context.Context, arg AddReclaimedChatTokensParams) error {
	_, err := q.db.Exec(ctx, addReclaimedChatTokens, arg.ReservedTokens, arg.Now, arg.GrantID)
	return err
}

const addReclaimedEmbeddingTokens = `-- name: AddReclaimedEmbeddingTokens :exec
UPDATE inference_grants
SET embedding_tokens = embedding_tokens + $1::bigint,
    updated_at = $2::timestamptz
WHERE grant_id = $3::uuid
`

type AddReclaimedEmbeddingTokensParams struct {
	ReservedTokens int64              `json:"reservedTokens"`
	Now            pgtype.Timestamptz `json:"now"`
	GrantID        pgtype.UUID        `json:"grantId"`
}

// Embedding-lane twin of AddReclaimedChatTokens.
func (q *Queries) AddReclaimedEmbeddingTokens(ctx context.Context, arg AddReclaimedEmbeddingTokensParams) error {
	_, err := q.db.Exec(ctx, addReclaimedEmbeddingTokens, arg.ReservedTokens, arg.Now, arg.GrantID)
	return err
}

const applyGrantChatSettlement = `-- name: ApplyGrantChatSettlement :one
UPDATE inference_grants
SET active_requests = $1::integer,
    prompt_tokens = prompt_tokens + $2::bigint,
    completion_tokens = completion_tokens + $3::bigint,
    cost_microusd = cost_microusd + $4::bigint,
    updated_at = $5::timestamptz
WHERE grant_id = $6::uuid
RETURNING grant_id, agent_id, bench_version, validator_hotkey, slot_id, ticket_deadline, status, bearer_digest, broker_public_key, generation, allowed_models, request_budget, token_budget, request_count, prompt_tokens, completion_tokens, cost_microusd, active_requests, expires_at, created_at, updated_at, route_provider, route_profile, route_quantization, route_prompt_price_per_token, route_completion_price_per_token, embedding_model, embedding_profile, embedding_provider, embedding_dimensions, embedding_request_budget, embedding_token_budget, embedding_request_count, embedding_tokens, embedding_cost_microusd, embedding_active_requests, usage_accounting_version
`

type ApplyGrantChatSettlementParams struct {
	ActiveRequests   int32              `json:"activeRequests"`
	PromptTokens     int64              `json:"promptTokens"`
	CompletionTokens int64              `json:"completionTokens"`
	CostMicrousd     int64              `json:"costMicrousd"`
	Now              pgtype.Timestamptz `json:"now"`
	GrantID          pgtype.UUID        `json:"grantId"`
}

// Settle-transaction grant accounting for the chat lane. active_requests is
// an ABSOLUTE value: the caller computes max(0, active_requests-1) from the
// locked row (the clamp lives in the application, matching Python, so the
// CHECK constraint never aborts the transaction). Spend columns are deltas.
// Returns the updated row so the caller can apply the chat token-budget
// exhaustion rule (prompt+completion >= token_budget -> exhausted) without
// re-reading.
func (q *Queries) ApplyGrantChatSettlement(ctx context.Context, arg ApplyGrantChatSettlementParams) (InferenceGrant, error) {
	row := q.db.QueryRow(ctx, applyGrantChatSettlement,
		arg.ActiveRequests,
		arg.PromptTokens,
		arg.CompletionTokens,
		arg.CostMicrousd,
		arg.Now,
		arg.GrantID,
	)
	var i InferenceGrant
	err := row.Scan(
		&i.GrantID,
		&i.AgentID,
		&i.BenchVersion,
		&i.ValidatorHotkey,
		&i.SlotID,
		&i.TicketDeadline,
		&i.Status,
		&i.BearerDigest,
		&i.BrokerPublicKey,
		&i.Generation,
		&i.AllowedModels,
		&i.RequestBudget,
		&i.TokenBudget,
		&i.RequestCount,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.CostMicrousd,
		&i.ActiveRequests,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RouteProvider,
		&i.RouteProfile,
		&i.RouteQuantization,
		&i.RoutePromptPricePerToken,
		&i.RouteCompletionPricePerToken,
		&i.EmbeddingModel,
		&i.EmbeddingProfile,
		&i.EmbeddingProvider,
		&i.EmbeddingDimensions,
		&i.EmbeddingRequestBudget,
		&i.EmbeddingTokenBudget,
		&i.EmbeddingRequestCount,
		&i.EmbeddingTokens,
		&i.EmbeddingCostMicrousd,
		&i.EmbeddingActiveRequests,
		&i.UsageAccountingVersion,
	)
	return i, err
}

const applyGrantEmbeddingSettlement = `-- name: ApplyGrantEmbeddingSettlement :one
UPDATE inference_grants
SET embedding_active_requests = $1::integer,
    embedding_tokens = embedding_tokens + $2::bigint,
    embedding_cost_microusd = embedding_cost_microusd + $3::bigint,
    updated_at = $4::timestamptz
WHERE grant_id = $5::uuid
RETURNING grant_id, agent_id, bench_version, validator_hotkey, slot_id, ticket_deadline, status, bearer_digest, broker_public_key, generation, allowed_models, request_budget, token_budget, request_count, prompt_tokens, completion_tokens, cost_microusd, active_requests, expires_at, created_at, updated_at, route_provider, route_profile, route_quantization, route_prompt_price_per_token, route_completion_price_per_token, embedding_model, embedding_profile, embedding_provider, embedding_dimensions, embedding_request_budget, embedding_token_budget, embedding_request_count, embedding_tokens, embedding_cost_microusd, embedding_active_requests, usage_accounting_version
`

type ApplyGrantEmbeddingSettlementParams struct {
	EmbeddingActiveRequests int32              `json:"embeddingActiveRequests"`
	EmbeddingTokens         int64              `json:"embeddingTokens"`
	EmbeddingCostMicrousd   int64              `json:"embeddingCostMicrousd"`
	Now                     pgtype.Timestamptz `json:"now"`
	GrantID                 pgtype.UUID        `json:"grantId"`
}

// Embedding-lane settle accounting. No exhaustion rule on this lane (killing
// the grant would take the chat lane down with it).
func (q *Queries) ApplyGrantEmbeddingSettlement(ctx context.Context, arg ApplyGrantEmbeddingSettlementParams) (InferenceGrant, error) {
	row := q.db.QueryRow(ctx, applyGrantEmbeddingSettlement,
		arg.EmbeddingActiveRequests,
		arg.EmbeddingTokens,
		arg.EmbeddingCostMicrousd,
		arg.Now,
		arg.GrantID,
	)
	var i InferenceGrant
	err := row.Scan(
		&i.GrantID,
		&i.AgentID,
		&i.BenchVersion,
		&i.ValidatorHotkey,
		&i.SlotID,
		&i.TicketDeadline,
		&i.Status,
		&i.BearerDigest,
		&i.BrokerPublicKey,
		&i.Generation,
		&i.AllowedModels,
		&i.RequestBudget,
		&i.TokenBudget,
		&i.RequestCount,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.CostMicrousd,
		&i.ActiveRequests,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RouteProvider,
		&i.RouteProfile,
		&i.RouteQuantization,
		&i.RoutePromptPricePerToken,
		&i.RouteCompletionPricePerToken,
		&i.EmbeddingModel,
		&i.EmbeddingProfile,
		&i.EmbeddingProvider,
		&i.EmbeddingDimensions,
		&i.EmbeddingRequestBudget,
		&i.EmbeddingTokenBudget,
		&i.EmbeddingRequestCount,
		&i.EmbeddingTokens,
		&i.EmbeddingCostMicrousd,
		&i.EmbeddingActiveRequests,
		&i.UsageAccountingVersion,
	)
	return i, err
}

const countFreshGlobalActiveRequests = `-- name: CountFreshGlobalActiveRequests :one
SELECT COUNT(*)::bigint
FROM inference_requests r
JOIN inference_grants g ON g.grant_id = r.grant_id
WHERE g.status = 'active'
  AND r.status = 'started'
  AND r.request_kind = $1::text
  AND r.started_at >= $2::timestamptz
`

type CountFreshGlobalActiveRequestsParams struct {
	RequestKind string             `json:"requestKind"`
	StaleCutoff pgtype.Timestamptz `json:"staleCutoff"`
}

// Cross-grant global concurrency rail; same fresh-row, best-effort semantics
// as CountFreshValidatorActiveRequests.
func (q *Queries) CountFreshGlobalActiveRequests(ctx context.Context, arg CountFreshGlobalActiveRequestsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countFreshGlobalActiveRequests, arg.RequestKind, arg.StaleCutoff)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countFreshValidatorActiveRequests = `-- name: CountFreshValidatorActiveRequests :one
SELECT COUNT(*)::bigint
FROM inference_requests r
JOIN inference_grants g ON g.grant_id = r.grant_id
WHERE g.status = 'active'
  AND r.status = 'started'
  AND r.request_kind = $1::text
  AND r.started_at >= $2::timestamptz
  AND g.validator_hotkey = $3::text
`

type CountFreshValidatorActiveRequestsParams struct {
	RequestKind     string             `json:"requestKind"`
	StaleCutoff     pgtype.Timestamptz `json:"staleCutoff"`
	ValidatorHotkey string             `json:"validatorHotkey"`
}

// Cross-grant per-validator concurrency rail (PR #735). Aggregates the
// authoritative request rows, not the denormalized grant counters: a
// validator ticket can expire before its scorer finishes the request, and
// older cleanup paths left the corresponding *_active_requests value behind
// on an otherwise-active grant — one such ghost permanently consumed a fleet
// concurrency slot. Only fresh 'started' rows (started_at >= the same
// 2*timeout recovery cutoff the stale sweep uses) on active grants count.
// DELIBERATELY unlocked and best-effort: a burst may overshoot by at most the
// number of racers. Do NOT add locks (a global advisory lock was removed
// because it capped horizontal scaling).
func (q *Queries) CountFreshValidatorActiveRequests(ctx context.Context, arg CountFreshValidatorActiveRequestsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countFreshValidatorActiveRequests, arg.RequestKind, arg.StaleCutoff, arg.ValidatorHotkey)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getInferenceGrant = `-- name: GetInferenceGrant :one

SELECT grant_id, agent_id, bench_version, validator_hotkey, slot_id, ticket_deadline, status, bearer_digest, broker_public_key, generation, allowed_models, request_budget, token_budget, request_count, prompt_tokens, completion_tokens, cost_microusd, active_requests, expires_at, created_at, updated_at, route_provider, route_profile, route_quantization, route_prompt_price_per_token, route_completion_price_per_token, embedding_model, embedding_profile, embedding_provider, embedding_dimensions, embedding_request_budget, embedding_token_budget, embedding_request_count, embedding_tokens, embedding_cost_microusd, embedding_active_requests, usage_accounting_version FROM inference_grants
WHERE grant_id = $1::uuid
`

// Inference grants: LOCK RANK 2. The grant row FOR UPDATE is THE
// serialization point for every per-grant budget invariant; all
// money-critical checks must be evaluated against the values returned by the
// locked read (GetInferenceGrantForUpdate), NEVER against an earlier
// unlocked snapshot (the Python populate_existing re-read is load-bearing —
// see test_reservations_on_one_grant_serialize_and_respect_the_budget).
//
// updated_at is application-maintained (no DB trigger); every UPDATE here
// sets it explicitly from the caller's clock, matching the ORM onupdate.
// Unlocked snapshot by grant id. Used only to learn the owning ticket PK (so
// the ticket can be locked FIRST, at rank 1) and for post-settle reads.
// Never evaluate budget gates against this row.
func (q *Queries) GetInferenceGrant(ctx context.Context, grantID pgtype.UUID) (InferenceGrant, error) {
	row := q.db.QueryRow(ctx, getInferenceGrant, grantID)
	var i InferenceGrant
	err := row.Scan(
		&i.GrantID,
		&i.AgentID,
		&i.BenchVersion,
		&i.ValidatorHotkey,
		&i.SlotID,
		&i.TicketDeadline,
		&i.Status,
		&i.BearerDigest,
		&i.BrokerPublicKey,
		&i.Generation,
		&i.AllowedModels,
		&i.RequestBudget,
		&i.TokenBudget,
		&i.RequestCount,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.CostMicrousd,
		&i.ActiveRequests,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RouteProvider,
		&i.RouteProfile,
		&i.RouteQuantization,
		&i.RoutePromptPricePerToken,
		&i.RouteCompletionPricePerToken,
		&i.EmbeddingModel,
		&i.EmbeddingProfile,
		&i.EmbeddingProvider,
		&i.EmbeddingDimensions,
		&i.EmbeddingRequestBudget,
		&i.EmbeddingTokenBudget,
		&i.EmbeddingRequestCount,
		&i.EmbeddingTokens,
		&i.EmbeddingCostMicrousd,
		&i.EmbeddingActiveRequests,
		&i.UsageAccountingVersion,
	)
	return i, err
}

const getInferenceGrantForUpdate = `-- name: GetInferenceGrantForUpdate :one
SELECT grant_id, agent_id, bench_version, validator_hotkey, slot_id, ticket_deadline, status, bearer_digest, broker_public_key, generation, allowed_models, request_budget, token_budget, request_count, prompt_tokens, completion_tokens, cost_microusd, active_requests, expires_at, created_at, updated_at, route_provider, route_profile, route_quantization, route_prompt_price_per_token, route_completion_price_per_token, embedding_model, embedding_profile, embedding_provider, embedding_dimensions, embedding_request_budget, embedding_token_budget, embedding_request_count, embedding_tokens, embedding_cost_microusd, embedding_active_requests, usage_accounting_version FROM inference_grants
WHERE grant_id = $1::uuid
FOR UPDATE
`

// Locked re-read (rank 2, after the ticket lock). All gate evaluation uses
// ONLY the values this returns.
func (q *Queries) GetInferenceGrantForUpdate(ctx context.Context, grantID pgtype.UUID) (InferenceGrant, error) {
	row := q.db.QueryRow(ctx, getInferenceGrantForUpdate, grantID)
	var i InferenceGrant
	err := row.Scan(
		&i.GrantID,
		&i.AgentID,
		&i.BenchVersion,
		&i.ValidatorHotkey,
		&i.SlotID,
		&i.TicketDeadline,
		&i.Status,
		&i.BearerDigest,
		&i.BrokerPublicKey,
		&i.Generation,
		&i.AllowedModels,
		&i.RequestBudget,
		&i.TokenBudget,
		&i.RequestCount,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.CostMicrousd,
		&i.ActiveRequests,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RouteProvider,
		&i.RouteProfile,
		&i.RouteQuantization,
		&i.RoutePromptPricePerToken,
		&i.RouteCompletionPricePerToken,
		&i.EmbeddingModel,
		&i.EmbeddingProfile,
		&i.EmbeddingProvider,
		&i.EmbeddingDimensions,
		&i.EmbeddingRequestBudget,
		&i.EmbeddingTokenBudget,
		&i.EmbeddingRequestCount,
		&i.EmbeddingTokens,
		&i.EmbeddingCostMicrousd,
		&i.EmbeddingActiveRequests,
		&i.UsageAccountingVersion,
	)
	return i, err
}

const incrementGrantChatAdmission = `-- name: IncrementGrantChatAdmission :exec
UPDATE inference_grants
SET request_count = request_count + 1,
    active_requests = active_requests + 1,
    updated_at = $1::timestamptz
WHERE grant_id = $2::uuid
`

type IncrementGrantChatAdmissionParams struct {
	Now     pgtype.Timestamptz `json:"now"`
	GrantID pgtype.UUID        `json:"grantId"`
}

// Admission bookkeeping after the request row INSERT: one more chat request
// admitted and in flight. Grant row is locked by the caller.
func (q *Queries) IncrementGrantChatAdmission(ctx context.Context, arg IncrementGrantChatAdmissionParams) error {
	_, err := q.db.Exec(ctx, incrementGrantChatAdmission, arg.Now, arg.GrantID)
	return err
}

const incrementGrantEmbeddingAdmission = `-- name: IncrementGrantEmbeddingAdmission :exec
UPDATE inference_grants
SET embedding_request_count = embedding_request_count + 1,
    embedding_active_requests = embedding_active_requests + 1,
    updated_at = $1::timestamptz
WHERE grant_id = $2::uuid
`

type IncrementGrantEmbeddingAdmissionParams struct {
	Now     pgtype.Timestamptz `json:"now"`
	GrantID pgtype.UUID        `json:"grantId"`
}

// Embedding-lane twin of IncrementGrantChatAdmission.
func (q *Queries) IncrementGrantEmbeddingAdmission(ctx context.Context, arg IncrementGrantEmbeddingAdmissionParams) error {
	_, err := q.db.Exec(ctx, incrementGrantEmbeddingAdmission, arg.Now, arg.GrantID)
	return err
}

const markInferenceGrantExhausted = `-- name: MarkInferenceGrantExhausted :exec
UPDATE inference_grants
SET status = 'exhausted',
    updated_at = $1::timestamptz
WHERE grant_id = $2::uuid
`

type MarkInferenceGrantExhaustedParams struct {
	Now     pgtype.Timestamptz `json:"now"`
	GrantID pgtype.UUID        `json:"grantId"`
}

// Terminal budget exhaustion. The committed writer in relay practice is the
// settle transaction (finish_inference_request).
func (q *Queries) MarkInferenceGrantExhausted(ctx context.Context, arg MarkInferenceGrantExhaustedParams) error {
	_, err := q.db.Exec(ctx, markInferenceGrantExhausted, arg.Now, arg.GrantID)
	return err
}

const revokeInferenceGrant = `-- name: RevokeInferenceGrant :exec
UPDATE inference_grants
SET status = 'revoked',
    updated_at = $1::timestamptz
WHERE grant_id = $2::uuid
`

type RevokeInferenceGrantParams struct {
	Now     pgtype.Timestamptz `json:"now"`
	GrantID pgtype.UUID        `json:"grantId"`
}

// Mid-lease revocation writer. Called by activate_inference_grant's validity
// gate (COMMITS via /exchange) and by begin_inference_request's
// ticket-liveness gate (rolls back on the relay endpoints, where declines
// abort the admission transaction). The platform reads status='revoked'
// deadline-scoped via ticket_inference_revoked_mid_lease.
func (q *Queries) RevokeInferenceGrant(ctx context.Context, arg RevokeInferenceGrantParams) error {
	_, err := q.db.Exec(ctx, revokeInferenceGrant, arg.Now, arg.GrantID)
	return err
}

const setGrantChatActiveRequests = `-- name: SetGrantChatActiveRequests :exec
UPDATE inference_grants
SET active_requests = $1::integer,
    updated_at = $2::timestamptz
WHERE grant_id = $3::uuid
`

type SetGrantChatActiveRequestsParams struct {
	ActiveRequests int32              `json:"activeRequests"`
	Now            pgtype.Timestamptz `json:"now"`
	GrantID        pgtype.UUID        `json:"grantId"`
}

// Post-reclamation lane recount (COUNT of still-started rows, computed by
// the caller via CountStartedInferenceRequests — a recount, not a
// decrement).
func (q *Queries) SetGrantChatActiveRequests(ctx context.Context, arg SetGrantChatActiveRequestsParams) error {
	_, err := q.db.Exec(ctx, setGrantChatActiveRequests, arg.ActiveRequests, arg.Now, arg.GrantID)
	return err
}

const setGrantEmbeddingActiveRequests = `-- name: SetGrantEmbeddingActiveRequests :exec
UPDATE inference_grants
SET embedding_active_requests = $1::integer,
    updated_at = $2::timestamptz
WHERE grant_id = $3::uuid
`

type SetGrantEmbeddingActiveRequestsParams struct {
	EmbeddingActiveRequests int32              `json:"embeddingActiveRequests"`
	Now                     pgtype.Timestamptz `json:"now"`
	GrantID                 pgtype.UUID        `json:"grantId"`
}

// Embedding-lane twin of SetGrantChatActiveRequests.
func (q *Queries) SetGrantEmbeddingActiveRequests(ctx context.Context, arg SetGrantEmbeddingActiveRequestsParams) error {
	_, err := q.db.Exec(ctx, setGrantEmbeddingActiveRequests, arg.EmbeddingActiveRequests, arg.Now, arg.GrantID)
	return err
}
