// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: inference_routes_queries.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getInferenceProviderRouteForUpdate = `-- name: GetInferenceProviderRouteForUpdate :one

SELECT model, provider, profile_revision, status, calibration_status, context_length, quantization, prompt_price_per_token, completion_price_per_token, ewma_tokens_per_second, ewma_latency_ms, ewma_error_rate, ewma_timeout_rate, ewma_tool_accuracy, ewma_composite, calibration_tool_accuracy, calibration_composite, calibration_sample_count, calibration_revision, calibration_manifest_sha256, calibrated_at, ewma_cost_microusd, sample_count, selected_ticket_count, exploration_ticket_count, last_selected_at, cooldown_until, discovered_at, last_observed_at, updated_at FROM inference_provider_routes
WHERE model = $1::text
  AND provider = $2::text
  AND profile_revision = $3::text
FOR UPDATE
`

type GetInferenceProviderRouteForUpdateParams struct {
	Model           string `json:"model"`
	Provider        string `json:"provider"`
	ProfileRevision string `json:"profileRevision"`
}

// Provider routes and routing policies. Route rows sit OUTSIDE the
// ticket->grant->request lock chain and are only ever locked singly, after
// the hot three, inside the chat settle transaction
// (record_route_observation). The relay never writes
// inference_routing_policies (platform admin owns them) and never touches
// routes on the embedding lane.
// Lock the route row a chat settle observes: PK is
// (model, provider, profile_revision) where model = grant.allowed_models[0],
// provider = grant.route_provider, profile_revision = grant.route_profile.
// Missing row => the observation is a no-op.
func (q *Queries) GetInferenceProviderRouteForUpdate(ctx context.Context, arg GetInferenceProviderRouteForUpdateParams) (InferenceProviderRoute, error) {
	row := q.db.QueryRow(ctx, getInferenceProviderRouteForUpdate, arg.Model, arg.Provider, arg.ProfileRevision)
	var i InferenceProviderRoute
	err := row.Scan(
		&i.Model,
		&i.Provider,
		&i.ProfileRevision,
		&i.Status,
		&i.CalibrationStatus,
		&i.ContextLength,
		&i.Quantization,
		&i.PromptPricePerToken,
		&i.CompletionPricePerToken,
		&i.EwmaTokensPerSecond,
		&i.EwmaLatencyMs,
		&i.EwmaErrorRate,
		&i.EwmaTimeoutRate,
		&i.EwmaToolAccuracy,
		&i.EwmaComposite,
		&i.CalibrationToolAccuracy,
		&i.CalibrationComposite,
		&i.CalibrationSampleCount,
		&i.CalibrationRevision,
		&i.CalibrationManifestSha256,
		&i.CalibratedAt,
		&i.EwmaCostMicrousd,
		&i.SampleCount,
		&i.SelectedTicketCount,
		&i.ExplorationTicketCount,
		&i.LastSelectedAt,
		&i.CooldownUntil,
		&i.DiscoveredAt,
		&i.LastObservedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInferenceRoutingPolicy = `-- name: GetInferenceRoutingPolicy :one
SELECT model, revision, enabled, speed_weight, cost_weight, exploration_weight, exploration_ticket_budget, min_tool_accuracy, min_composite, min_calibration_samples, max_error_rate, max_timeout_rate, cooldown_seconds, ewma_alpha, updated_at, gateway_provider_order FROM inference_routing_policies
WHERE model = $1::text
`

// Unlocked policy read (EWMA alpha, cooldown). Missing row => observation
// no-op.
func (q *Queries) GetInferenceRoutingPolicy(ctx context.Context, model string) (InferenceRoutingPolicy, error) {
	row := q.db.QueryRow(ctx, getInferenceRoutingPolicy, model)
	var i InferenceRoutingPolicy
	err := row.Scan(
		&i.Model,
		&i.Revision,
		&i.Enabled,
		&i.SpeedWeight,
		&i.CostWeight,
		&i.ExplorationWeight,
		&i.ExplorationTicketBudget,
		&i.MinToolAccuracy,
		&i.MinComposite,
		&i.MinCalibrationSamples,
		&i.MaxErrorRate,
		&i.MaxTimeoutRate,
		&i.CooldownSeconds,
		&i.EwmaAlpha,
		&i.UpdatedAt,
		&i.GatewayProviderOrder,
	)
	return i, err
}

const updateInferenceProviderRouteObservation = `-- name: UpdateInferenceProviderRouteObservation :exec
UPDATE inference_provider_routes
SET sample_count = $1::bigint,
    ewma_latency_ms = $2::double precision,
    ewma_tokens_per_second = $3::double precision,
    ewma_error_rate = $4::double precision,
    ewma_timeout_rate = $5::double precision,
    ewma_cost_microusd = $6::double precision,
    status = $7::text,
    cooldown_until = $8::timestamptz,
    last_observed_at = $9::timestamptz,
    updated_at = $10::timestamptz
WHERE model = $11::text
  AND provider = $12::text
  AND profile_revision = $13::text
`

type UpdateInferenceProviderRouteObservationParams struct {
	SampleCount         int64              `json:"sampleCount"`
	EwmaLatencyMs       pgtype.Float8      `json:"ewmaLatencyMs"`
	EwmaTokensPerSecond pgtype.Float8      `json:"ewmaTokensPerSecond"`
	EwmaErrorRate       float64            `json:"ewmaErrorRate"`
	EwmaTimeoutRate     float64            `json:"ewmaTimeoutRate"`
	EwmaCostMicrousd    pgtype.Float8      `json:"ewmaCostMicrousd"`
	Status              string             `json:"status"`
	CooldownUntil       pgtype.Timestamptz `json:"cooldownUntil"`
	LastObservedAt      pgtype.Timestamptz `json:"lastObservedAt"`
	Now                 pgtype.Timestamptz `json:"now"`
	Model               string             `json:"model"`
	Provider            string             `json:"provider"`
	ProfileRevision     string             `json:"profileRevision"`
}

// Write back one chat-settle observation. Every value is computed by the
// caller from the LOCKED route row + policy (EWMA folds, healthy/degraded
// status, cooldown_until = now + policy.cooldown_seconds on failure and NULL
// on success), so this is a plain absolute-value write.
func (q *Queries) UpdateInferenceProviderRouteObservation(ctx context.Context, arg UpdateInferenceProviderRouteObservationParams) error {
	_, err := q.db.Exec(ctx, updateInferenceProviderRouteObservation,
		arg.SampleCount,
		arg.EwmaLatencyMs,
		arg.EwmaTokensPerSecond,
		arg.EwmaErrorRate,
		arg.EwmaTimeoutRate,
		arg.EwmaCostMicrousd,
		arg.Status,
		arg.CooldownUntil,
		arg.LastObservedAt,
		arg.Now,
		arg.Model,
		arg.Provider,
		arg.ProfileRevision,
	)
	return err
}
