// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: miner_ditto_links_queries.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getActiveMinerDittoLinkForAgent = `-- name: GetActiveMinerDittoLinkForAgent :one

SELECT l.miner_hotkey, l.ditto_user_id, l.ditto_email, l.linked_via
FROM agents a
JOIN miner_ditto_links l ON l.miner_hotkey = a.miner_hotkey
WHERE a.agent_id = $1::uuid
  AND l.revoked_at IS NULL
`

type GetActiveMinerDittoLinkForAgentRow struct {
	MinerHotkey string      `json:"minerHotkey"`
	DittoUserID string      `json:"dittoUserId"`
	DittoEmail  pgtype.Text `json:"dittoEmail"`
	LinkedVia   string      `json:"linkedVia"`
}

// Miner ↔ Ditto account links (apps/platform migration 7a2c91d4e5f0). Read-only
// here: the Platform owns linking; the relay only asks "does this agent's
// miner have a consenting Ditto account?" to attribute a Ditto Router call.
// No lock: the row is advisory attribution, never a budget gate.
func (q *Queries) GetActiveMinerDittoLinkForAgent(ctx context.Context, agentID pgtype.UUID) (GetActiveMinerDittoLinkForAgentRow, error) {
	row := q.db.QueryRow(ctx, getActiveMinerDittoLinkForAgent, agentID)
	var i GetActiveMinerDittoLinkForAgentRow
	err := row.Scan(
		&i.MinerHotkey,
		&i.DittoUserID,
		&i.DittoEmail,
		&i.LinkedVia,
	)
	return i, err
}
