// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: provider_outage_queries.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const closeProviderOutageCircuit = `-- name: CloseProviderOutageCircuit :execrows
UPDATE provider_outage_circuits
SET state = 'closed',
    closed_at = $1::timestamptz,
    probe_kind = NULL,
    probe_key = NULL,
    probe_expires_at = NULL,
    updated_at = $1::timestamptz
WHERE provider = $2::text
  AND state = 'open'
  AND last_failure_at <= $3::timestamptz
`

type CloseProviderOutageCircuitParams struct {
	Now              pgtype.Timestamptz `json:"now"`
	Provider         string             `json:"provider"`
	RequestStartedAt pgtype.Timestamptz `json:"requestStartedAt"`
}

func (q *Queries) CloseProviderOutageCircuit(ctx context.Context, arg CloseProviderOutageCircuitParams) (int64, error) {
	result, err := q.db.Exec(ctx, closeProviderOutageCircuit, arg.Now, arg.Provider, arg.RequestStartedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const openProviderOutageCircuit = `-- name: OpenProviderOutageCircuit :one

INSERT INTO provider_outage_circuits (
    provider, state, epoch, opened_at, retry_at, last_failure_at,
    failure_count, last_status, last_error_code, updated_at
) VALUES (
    $1::text,
    'open',
    $2::uuid,
    $3::timestamptz,
    $4::timestamptz,
    $3::timestamptz,
    1,
    $5::integer,
    $6::text,
    $3::timestamptz
)
ON CONFLICT (provider) DO UPDATE SET
    state = 'open',
    epoch = CASE
        WHEN provider_outage_circuits.state = 'closed' THEN EXCLUDED.epoch
        ELSE provider_outage_circuits.epoch
    END,
    opened_at = CASE
        WHEN provider_outage_circuits.state = 'closed' THEN EXCLUDED.opened_at
        ELSE provider_outage_circuits.opened_at
    END,
    retry_at = GREATEST(provider_outage_circuits.retry_at, EXCLUDED.retry_at),
    last_failure_at = GREATEST(
        provider_outage_circuits.last_failure_at,
        EXCLUDED.last_failure_at
    ),
    closed_at = NULL,
    failure_count = CASE
        WHEN provider_outage_circuits.state = 'closed' THEN 1
        ELSE provider_outage_circuits.failure_count + 1
    END,
    last_status = CASE
        WHEN EXCLUDED.last_failure_at >= provider_outage_circuits.last_failure_at
        THEN EXCLUDED.last_status
        ELSE provider_outage_circuits.last_status
    END,
    last_error_code = CASE
        WHEN EXCLUDED.last_failure_at >= provider_outage_circuits.last_failure_at
        THEN EXCLUDED.last_error_code
        ELSE provider_outage_circuits.last_error_code
    END,
    probe_kind = NULL,
    probe_key = NULL,
    probe_expires_at = NULL,
    updated_at = GREATEST(provider_outage_circuits.updated_at, EXCLUDED.updated_at)
RETURNING provider, state, epoch, opened_at, retry_at, last_failure_at, closed_at, failure_count, last_status, last_error_code, probe_kind, probe_key, probe_expires_at, updated_at
`

type OpenProviderOutageCircuitParams struct {
	Provider      string             `json:"provider"`
	Epoch         pgtype.UUID        `json:"epoch"`
	Now           pgtype.Timestamptz `json:"now"`
	RetryAt       pgtype.Timestamptz `json:"retryAt"`
	LastStatus    pgtype.Int4        `json:"lastStatus"`
	LastErrorCode string             `json:"lastErrorCode"`
}

// Relay-owned provider-wide overload circuit. Platform consumes this row to
// park scoring and screening leases; no Platform writer opens or closes it.
func (q *Queries) OpenProviderOutageCircuit(ctx context.Context, arg OpenProviderOutageCircuitParams) (ProviderOutageCircuit, error) {
	row := q.db.QueryRow(ctx, openProviderOutageCircuit,
		arg.Provider,
		arg.Epoch,
		arg.Now,
		arg.RetryAt,
		arg.LastStatus,
		arg.LastErrorCode,
	)
	var i ProviderOutageCircuit
	err := row.Scan(
		&i.Provider,
		&i.State,
		&i.Epoch,
		&i.OpenedAt,
		&i.RetryAt,
		&i.LastFailureAt,
		&i.ClosedAt,
		&i.FailureCount,
		&i.LastStatus,
		&i.LastErrorCode,
		&i.ProbeKind,
		&i.ProbeKey,
		&i.ProbeExpiresAt,
		&i.UpdatedAt,
	)
	return i, err
}
