// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: source_review_queries.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getSourceReviewProviderEventAuth = `-- name: GetSourceReviewProviderEventAuth :one
SELECT review_id, status, job_token_hash, job_token_expires_at
FROM submission_source_reviews
WHERE review_id = $1::uuid
`

type GetSourceReviewProviderEventAuthRow struct {
	ReviewID          pgtype.UUID        `json:"reviewId"`
	Status            string             `json:"status"`
	JobTokenHash      pgtype.Text        `json:"jobTokenHash"`
	JobTokenExpiresAt pgtype.Timestamptz `json:"jobTokenExpiresAt"`
}

func (q *Queries) GetSourceReviewProviderEventAuth(ctx context.Context, reviewID pgtype.UUID) (GetSourceReviewProviderEventAuthRow, error) {
	row := q.db.QueryRow(ctx, getSourceReviewProviderEventAuth, reviewID)
	var i GetSourceReviewProviderEventAuthRow
	err := row.Scan(
		&i.ReviewID,
		&i.Status,
		&i.JobTokenHash,
		&i.JobTokenExpiresAt,
	)
	return i, err
}
