// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: trace_backfill_queries.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteBackfilledConfirmationInferenceRequests = `-- name: DeleteBackfilledConfirmationInferenceRequests :execrows
DELETE FROM confirmation_inference_requests r
 USING confirmation_inference_grants g
 WHERE g.grant_id = r.grant_id
   AND (r.started_at, r.grant_id, r.nonce) >= ($1::timestamptz, $2::uuid, $3::uuid)
   AND (r.started_at, r.grant_id, r.nonce) <= ($4::timestamptz, $5::uuid, $6::uuid)
   AND r.status <> 'started'
   AND r.started_at < $7::timestamptz
   AND g.expires_at < $7::timestamptz
`

type DeleteBackfilledConfirmationInferenceRequestsParams struct {
	FromStartedAt pgtype.Timestamptz `json:"fromStartedAt"`
	FromGrantID   pgtype.UUID        `json:"fromGrantId"`
	FromNonce     pgtype.UUID        `json:"fromNonce"`
	ToStartedAt   pgtype.Timestamptz `json:"toStartedAt"`
	ToGrantID     pgtype.UUID        `json:"toGrantId"`
	ToNonce       pgtype.UUID        `json:"toNonce"`
	RetainBefore  pgtype.Timestamptz `json:"retainBefore"`
}

func (q *Queries) DeleteBackfilledConfirmationInferenceRequests(ctx context.Context, arg DeleteBackfilledConfirmationInferenceRequestsParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBackfilledConfirmationInferenceRequests,
		arg.FromStartedAt,
		arg.FromGrantID,
		arg.FromNonce,
		arg.ToStartedAt,
		arg.ToGrantID,
		arg.ToNonce,
		arg.RetainBefore,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteBackfilledInferenceRequests = `-- name: DeleteBackfilledInferenceRequests :execrows
DELETE FROM inference_requests r
 USING inference_grants g
 WHERE g.grant_id = r.grant_id
   AND (r.started_at, r.grant_id, r.nonce) >= ($1::timestamptz, $2::uuid, $3::uuid)
   AND (r.started_at, r.grant_id, r.nonce) <= ($4::timestamptz, $5::uuid, $6::uuid)
   AND r.status <> 'started'
   AND r.started_at < $7::timestamptz
   AND g.expires_at < $7::timestamptz
`

type DeleteBackfilledInferenceRequestsParams struct {
	FromStartedAt pgtype.Timestamptz `json:"fromStartedAt"`
	FromGrantID   pgtype.UUID        `json:"fromGrantId"`
	FromNonce     pgtype.UUID        `json:"fromNonce"`
	ToStartedAt   pgtype.Timestamptz `json:"toStartedAt"`
	ToGrantID     pgtype.UUID        `json:"toGrantId"`
	ToNonce       pgtype.UUID        `json:"toNonce"`
	RetainBefore  pgtype.Timestamptz `json:"retainBefore"`
}

func (q *Queries) DeleteBackfilledInferenceRequests(ctx context.Context, arg DeleteBackfilledInferenceRequestsParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBackfilledInferenceRequests,
		arg.FromStartedAt,
		arg.FromGrantID,
		arg.FromNonce,
		arg.ToStartedAt,
		arg.ToGrantID,
		arg.ToNonce,
		arg.RetainBefore,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listConfirmationInferenceRequestsForBackfill = `-- name: ListConfirmationInferenceRequestsForBackfill :many
SELECT r.grant_id, r.nonce, r.generation, r.status, r.model, r.reserved_tokens,
       r.max_chargeable_tokens, r.prompt_tokens, r.completion_tokens,
       r.cost_microusd, r.upstream_provider, r.started_at, r.completed_at,
       g.ticket_id, g.bundle_id, g.validator_hotkey, g.lane,
       g.status AS grant_status, g.generation AS grant_generation,
       g.model AS grant_model, g.provider, g.route_provider,
       g.receipt_provider, g.profile_revision,
       g.expires_at AS grant_expires_at
  FROM confirmation_inference_requests r
  JOIN confirmation_inference_grants g ON g.grant_id = r.grant_id
 WHERE (r.started_at, r.grant_id, r.nonce) > ($1::timestamptz, $2::uuid, $3::uuid)
   AND r.started_at < $4::timestamptz
 ORDER BY r.started_at, r.grant_id, r.nonce
 LIMIT $5
`

type ListConfirmationInferenceRequestsForBackfillParams struct {
	AfterStartedAt pgtype.Timestamptz `json:"afterStartedAt"`
	AfterGrantID   pgtype.UUID        `json:"afterGrantId"`
	AfterNonce     pgtype.UUID        `json:"afterNonce"`
	Until          pgtype.Timestamptz `json:"until"`
	BatchLimit     int32              `json:"batchLimit"`
}

type ListConfirmationInferenceRequestsForBackfillRow struct {
	GrantID             pgtype.UUID        `json:"grantId"`
	Nonce               pgtype.UUID        `json:"nonce"`
	Generation          int32              `json:"generation"`
	Status              string             `json:"status"`
	Model               string             `json:"model"`
	ReservedTokens      int64              `json:"reservedTokens"`
	MaxChargeableTokens int64              `json:"maxChargeableTokens"`
	PromptTokens        int64              `json:"promptTokens"`
	CompletionTokens    int64              `json:"completionTokens"`
	CostMicrousd        int64              `json:"costMicrousd"`
	UpstreamProvider    pgtype.Text        `json:"upstreamProvider"`
	StartedAt           pgtype.Timestamptz `json:"startedAt"`
	CompletedAt         pgtype.Timestamptz `json:"completedAt"`
	TicketID            pgtype.UUID        `json:"ticketId"`
	BundleID            pgtype.UUID        `json:"bundleId"`
	ValidatorHotkey     string             `json:"validatorHotkey"`
	Lane                string             `json:"lane"`
	GrantStatus         string             `json:"grantStatus"`
	GrantGeneration     int32              `json:"grantGeneration"`
	GrantModel          string             `json:"grantModel"`
	Provider            string             `json:"provider"`
	RouteProvider       string             `json:"routeProvider"`
	ReceiptProvider     string             `json:"receiptProvider"`
	ProfileRevision     string             `json:"profileRevision"`
	GrantExpiresAt      pgtype.Timestamptz `json:"grantExpiresAt"`
}

func (q *Queries) ListConfirmationInferenceRequestsForBackfill(ctx context.Context, arg ListConfirmationInferenceRequestsForBackfillParams) ([]ListConfirmationInferenceRequestsForBackfillRow, error) {
	rows, err := q.db.Query(ctx, listConfirmationInferenceRequestsForBackfill,
		arg.AfterStartedAt,
		arg.AfterGrantID,
		arg.AfterNonce,
		arg.Until,
		arg.BatchLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListConfirmationInferenceRequestsForBackfillRow
	for rows.Next() {
		var i ListConfirmationInferenceRequestsForBackfillRow
		if err := rows.Scan(
			&i.GrantID,
			&i.Nonce,
			&i.Generation,
			&i.Status,
			&i.Model,
			&i.ReservedTokens,
			&i.MaxChargeableTokens,
			&i.PromptTokens,
			&i.CompletionTokens,
			&i.CostMicrousd,
			&i.UpstreamProvider,
			&i.StartedAt,
			&i.CompletedAt,
			&i.TicketID,
			&i.BundleID,
			&i.ValidatorHotkey,
			&i.Lane,
			&i.GrantStatus,
			&i.GrantGeneration,
			&i.GrantModel,
			&i.Provider,
			&i.RouteProvider,
			&i.ReceiptProvider,
			&i.ProfileRevision,
			&i.GrantExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInferenceRequestsForBackfill = `-- name: ListInferenceRequestsForBackfill :many

SELECT r.grant_id, r.nonce, r.generation, r.status, r.model, r.reserved_tokens,
       r.max_chargeable_tokens, r.prompt_tokens, r.completion_tokens,
       r.cost_microusd, r.started_at, r.completed_at, r.upstream_provider,
       r.timed_out, r.latency_ms, r.request_kind, r.upstream_attempts,
       r.openrouter_attempts, r.fallback_phase, r.terminal_error_code,
       g.agent_id, g.bench_version, g.validator_hotkey, g.slot_id,
       g.ticket_deadline, g.status AS grant_status,
       g.generation AS grant_generation, g.allowed_models, g.route_provider,
       g.route_profile, g.route_quantization, g.expires_at AS grant_expires_at
  FROM inference_requests r
  JOIN inference_grants g ON g.grant_id = r.grant_id
 WHERE (r.started_at, r.grant_id, r.nonce) > ($1::timestamptz, $2::uuid, $3::uuid)
   AND r.started_at < $4::timestamptz
 ORDER BY r.started_at, r.grant_id, r.nonce
 LIMIT $5
`

type ListInferenceRequestsForBackfillParams struct {
	AfterStartedAt pgtype.Timestamptz `json:"afterStartedAt"`
	AfterGrantID   pgtype.UUID        `json:"afterGrantId"`
	AfterNonce     pgtype.UUID        `json:"afterNonce"`
	Until          pgtype.Timestamptz `json:"until"`
	BatchLimit     int32              `json:"batchLimit"`
}

type ListInferenceRequestsForBackfillRow struct {
	GrantID             pgtype.UUID        `json:"grantId"`
	Nonce               pgtype.UUID        `json:"nonce"`
	Generation          int32              `json:"generation"`
	Status              string             `json:"status"`
	Model               string             `json:"model"`
	ReservedTokens      int64              `json:"reservedTokens"`
	MaxChargeableTokens int64              `json:"maxChargeableTokens"`
	PromptTokens        int64              `json:"promptTokens"`
	CompletionTokens    int64              `json:"completionTokens"`
	CostMicrousd        int64              `json:"costMicrousd"`
	StartedAt           pgtype.Timestamptz `json:"startedAt"`
	CompletedAt         pgtype.Timestamptz `json:"completedAt"`
	UpstreamProvider    pgtype.Text        `json:"upstreamProvider"`
	TimedOut            bool               `json:"timedOut"`
	LatencyMs           pgtype.Int4        `json:"latencyMs"`
	RequestKind         string             `json:"requestKind"`
	UpstreamAttempts    int32              `json:"upstreamAttempts"`
	OpenrouterAttempts  int32              `json:"openrouterAttempts"`
	FallbackPhase       int32              `json:"fallbackPhase"`
	TerminalErrorCode   pgtype.Text        `json:"terminalErrorCode"`
	AgentID             pgtype.UUID        `json:"agentId"`
	BenchVersion        int32              `json:"benchVersion"`
	ValidatorHotkey     string             `json:"validatorHotkey"`
	SlotID              string             `json:"slotId"`
	TicketDeadline      pgtype.Timestamptz `json:"ticketDeadline"`
	GrantStatus         string             `json:"grantStatus"`
	GrantGeneration     int32              `json:"grantGeneration"`
	AllowedModels       []byte             `json:"allowedModels"`
	RouteProvider       pgtype.Text        `json:"routeProvider"`
	RouteProfile        pgtype.Text        `json:"routeProfile"`
	RouteQuantization   pgtype.Text        `json:"routeQuantization"`
	GrantExpiresAt      pgtype.Timestamptz `json:"grantExpiresAt"`
}

// Trace backfill reads: keyset-paginated walks of the inference ledgers joined
// to their grants, in (started_at, grant_id, nonce) order, used by
// `model-relay trace-backfill` to export historical rows (metadata only; the
// relay never stored bodies before the trace capture existed) to the trace
// buckets. The optional delete is bounded to the exact key range an exported
// batch covered and to rows no live grant can still touch.
//
// Lock order: reads only; the delete touches inference_requests alone
// (rank 3) and never a grant row.
func (q *Queries) ListInferenceRequestsForBackfill(ctx context.Context, arg ListInferenceRequestsForBackfillParams) ([]ListInferenceRequestsForBackfillRow, error) {
	rows, err := q.db.Query(ctx, listInferenceRequestsForBackfill,
		arg.AfterStartedAt,
		arg.AfterGrantID,
		arg.AfterNonce,
		arg.Until,
		arg.BatchLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInferenceRequestsForBackfillRow
	for rows.Next() {
		var i ListInferenceRequestsForBackfillRow
		if err := rows.Scan(
			&i.GrantID,
			&i.Nonce,
			&i.Generation,
			&i.Status,
			&i.Model,
			&i.ReservedTokens,
			&i.MaxChargeableTokens,
			&i.PromptTokens,
			&i.CompletionTokens,
			&i.CostMicrousd,
			&i.StartedAt,
			&i.CompletedAt,
			&i.UpstreamProvider,
			&i.TimedOut,
			&i.LatencyMs,
			&i.RequestKind,
			&i.UpstreamAttempts,
			&i.OpenrouterAttempts,
			&i.FallbackPhase,
			&i.TerminalErrorCode,
			&i.AgentID,
			&i.BenchVersion,
			&i.ValidatorHotkey,
			&i.SlotID,
			&i.TicketDeadline,
			&i.GrantStatus,
			&i.GrantGeneration,
			&i.AllowedModels,
			&i.RouteProvider,
			&i.RouteProfile,
			&i.RouteQuantization,
			&i.GrantExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
