// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: upload_queries.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteUploadAdmission = `-- name: DeleteUploadAdmission :exec
DELETE FROM upload_admission_reservations WHERE miner_coldkey = $1
`

func (q *Queries) DeleteUploadAdmission(ctx context.Context, minerColdkey string) error {
	_, err := q.db.Exec(ctx, deleteUploadAdmission, minerColdkey)
	return err
}

const getLatestSubmissionDepositAddress = `-- name: GetLatestSubmissionDepositAddress :one
SELECT payment_address
FROM submission_deposit_address_revisions
ORDER BY revision DESC
LIMIT 1
`

func (q *Queries) GetLatestSubmissionDepositAddress(ctx context.Context) (string, error) {
	row := q.db.QueryRow(ctx, getLatestSubmissionDepositAddress)
	var payment_address string
	err := row.Scan(&payment_address)
	return payment_address, err
}

const getLatestSubmissionSettings = `-- name: GetLatestSubmissionSettings :one
SELECT revision, cooldown_seconds, fee_amount_rao
FROM submission_settings_revisions
ORDER BY revision DESC
LIMIT 1
`

type GetLatestSubmissionSettingsRow struct {
	Revision        int32 `json:"revision"`
	CooldownSeconds int32 `json:"cooldownSeconds"`
	FeeAmountRao    int64 `json:"feeAmountRao"`
}

func (q *Queries) GetLatestSubmissionSettings(ctx context.Context) (GetLatestSubmissionSettingsRow, error) {
	row := q.db.QueryRow(ctx, getLatestSubmissionSettings)
	var i GetLatestSubmissionSettingsRow
	err := row.Scan(&i.Revision, &i.CooldownSeconds, &i.FeeAmountRao)
	return i, err
}

const getSameHotkeyAgentBySHA = `-- name: GetSameHotkeyAgentBySHA :one
SELECT a.agent_id, a.status::text AS status
FROM agents AS a
JOIN evaluation_payments AS p ON p.agent_id = a.agent_id
WHERE a.miner_hotkey = $1 AND a.sha256 = $2
ORDER BY a.created_at ASC, a.agent_id ASC
LIMIT 1
`

type GetSameHotkeyAgentBySHAParams struct {
	MinerHotkey string `json:"minerHotkey"`
	Sha256      string `json:"sha256"`
}

type GetSameHotkeyAgentBySHARow struct {
	AgentID pgtype.UUID `json:"agentId"`
	Status  string      `json:"status"`
}

func (q *Queries) GetSameHotkeyAgentBySHA(ctx context.Context, arg GetSameHotkeyAgentBySHAParams) (GetSameHotkeyAgentBySHARow, error) {
	row := q.db.QueryRow(ctx, getSameHotkeyAgentBySHA, arg.MinerHotkey, arg.Sha256)
	var i GetSameHotkeyAgentBySHARow
	err := row.Scan(&i.AgentID, &i.Status)
	return i, err
}

const getSubmissionLatestPaidCreatedAt = `-- name: GetSubmissionLatestPaidCreatedAt :one
SELECT max(a.created_at)::timestamptz
FROM agents AS a
JOIN evaluation_payments AS p ON p.agent_id = a.agent_id
WHERE p.miner_coldkey = $1
`

func (q *Queries) GetSubmissionLatestPaidCreatedAt(ctx context.Context, minerColdkey string) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getSubmissionLatestPaidCreatedAt, minerColdkey)
	var column_1 pgtype.Timestamptz
	err := row.Scan(&column_1)
	return column_1, err
}

const getUploadAdmissionForColdkey = `-- name: GetUploadAdmissionForColdkey :one
SELECT miner_coldkey, token, miner_hotkey, sha256, settings_revision,
       cooldown_seconds, fee_amount_rao, payment_send_address,
       legacy_payment_cutoff_at, created_at, expires_at
FROM upload_admission_reservations
WHERE miner_coldkey = $1
FOR UPDATE
`

type GetUploadAdmissionForColdkeyRow struct {
	MinerColdkey          string             `json:"minerColdkey"`
	Token                 pgtype.UUID        `json:"token"`
	MinerHotkey           string             `json:"minerHotkey"`
	Sha256                string             `json:"sha256"`
	SettingsRevision      int32              `json:"settingsRevision"`
	CooldownSeconds       int32              `json:"cooldownSeconds"`
	FeeAmountRao          int64              `json:"feeAmountRao"`
	PaymentSendAddress    pgtype.Text        `json:"paymentSendAddress"`
	LegacyPaymentCutoffAt pgtype.Timestamptz `json:"legacyPaymentCutoffAt"`
	CreatedAt             pgtype.Timestamptz `json:"createdAt"`
	ExpiresAt             pgtype.Timestamptz `json:"expiresAt"`
}

func (q *Queries) GetUploadAdmissionForColdkey(ctx context.Context, minerColdkey string) (GetUploadAdmissionForColdkeyRow, error) {
	row := q.db.QueryRow(ctx, getUploadAdmissionForColdkey, minerColdkey)
	var i GetUploadAdmissionForColdkeyRow
	err := row.Scan(
		&i.MinerColdkey,
		&i.Token,
		&i.MinerHotkey,
		&i.Sha256,
		&i.SettingsRevision,
		&i.CooldownSeconds,
		&i.FeeAmountRao,
		&i.PaymentSendAddress,
		&i.LegacyPaymentCutoffAt,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const insertUploadAdmission = `-- name: InsertUploadAdmission :one
INSERT INTO upload_admission_reservations (
    miner_coldkey, token, miner_hotkey, sha256, settings_revision,
    cooldown_seconds, fee_amount_rao, payment_send_address,
    legacy_payment_cutoff_at, created_at, expires_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, NULL, $9, $10)
RETURNING miner_coldkey, token, miner_hotkey, sha256, settings_revision,
          cooldown_seconds, fee_amount_rao, payment_send_address,
          legacy_payment_cutoff_at, created_at, expires_at
`

type InsertUploadAdmissionParams struct {
	MinerColdkey       string             `json:"minerColdkey"`
	Token              pgtype.UUID        `json:"token"`
	MinerHotkey        string             `json:"minerHotkey"`
	Sha256             string             `json:"sha256"`
	SettingsRevision   int32              `json:"settingsRevision"`
	CooldownSeconds    int32              `json:"cooldownSeconds"`
	FeeAmountRao       int64              `json:"feeAmountRao"`
	PaymentSendAddress pgtype.Text        `json:"paymentSendAddress"`
	CreatedAt          pgtype.Timestamptz `json:"createdAt"`
	ExpiresAt          pgtype.Timestamptz `json:"expiresAt"`
}

type InsertUploadAdmissionRow struct {
	MinerColdkey          string             `json:"minerColdkey"`
	Token                 pgtype.UUID        `json:"token"`
	MinerHotkey           string             `json:"minerHotkey"`
	Sha256                string             `json:"sha256"`
	SettingsRevision      int32              `json:"settingsRevision"`
	CooldownSeconds       int32              `json:"cooldownSeconds"`
	FeeAmountRao          int64              `json:"feeAmountRao"`
	PaymentSendAddress    pgtype.Text        `json:"paymentSendAddress"`
	LegacyPaymentCutoffAt pgtype.Timestamptz `json:"legacyPaymentCutoffAt"`
	CreatedAt             pgtype.Timestamptz `json:"createdAt"`
	ExpiresAt             pgtype.Timestamptz `json:"expiresAt"`
}

func (q *Queries) InsertUploadAdmission(ctx context.Context, arg InsertUploadAdmissionParams) (InsertUploadAdmissionRow, error) {
	row := q.db.QueryRow(ctx, insertUploadAdmission,
		arg.MinerColdkey,
		arg.Token,
		arg.MinerHotkey,
		arg.Sha256,
		arg.SettingsRevision,
		arg.CooldownSeconds,
		arg.FeeAmountRao,
		arg.PaymentSendAddress,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	var i InsertUploadAdmissionRow
	err := row.Scan(
		&i.MinerColdkey,
		&i.Token,
		&i.MinerHotkey,
		&i.Sha256,
		&i.SettingsRevision,
		&i.CooldownSeconds,
		&i.FeeAmountRao,
		&i.PaymentSendAddress,
		&i.LegacyPaymentCutoffAt,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const isHotkeyBanned = `-- name: IsHotkeyBanned :one
SELECT EXISTS (
    SELECT 1 FROM banned_hotkeys WHERE hotkey = $1
) AS banned
`

func (q *Queries) IsHotkeyBanned(ctx context.Context, hotkey string) (bool, error) {
	row := q.db.QueryRow(ctx, isHotkeyBanned, hotkey)
	var banned bool
	err := row.Scan(&banned)
	return banned, err
}

const lockUploadAdmissionColdkey = `-- name: LockUploadAdmissionColdkey :exec
SELECT pg_advisory_xact_lock(hashtextextended($1, 0))
`

func (q *Queries) LockUploadAdmissionColdkey(ctx context.Context, hashtextextended string) error {
	_, err := q.db.Exec(ctx, lockUploadAdmissionColdkey, hashtextextended)
	return err
}
