// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: validator_tickets_queries.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getValidatorTicketForUpdate = `-- name: GetValidatorTicketForUpdate :one

SELECT agent_id, validator_hotkey, status, issued_at, deadline, created_at, updated_at, bench_version, attempt_count, retry_after, manual_retry_grants, infra_retry_grants, slot_id, purpose, legacy_completion_allowed, purpose_revision, seed, dataset_sha256, seed_block, seed_block_hash, failure_reason, failed_at, first_reported_at, failure_detail, container_log_tail FROM validator_tickets
WHERE agent_id = $1::uuid
  AND bench_version = $2::integer
  AND validator_hotkey = $3::text
FOR UPDATE
`

type GetValidatorTicketForUpdateParams struct {
	AgentID         pgtype.UUID `json:"agentId"`
	BenchVersion    int32       `json:"benchVersion"`
	ValidatorHotkey string      `json:"validatorHotkey"`
}

// Validator tickets: LOCK RANK 1 of the repo-wide hot-table lock order
// validator_tickets -> inference_grants -> inference_requests. Every relay
// transaction that will lock a grant row MUST lock the owning ticket row
// first (activate_inference_grant, begin_inference_request,
// finish_inference_request all do). The relay never updates ticket data
// columns — it only locks the row and reads its liveness fields.
// Lock and read the ticket that owns a grant (composite PK). Zero rows is a
// legal outcome (ticket deleted): callers treat pgx.ErrNoRows as
// "ticket missing" and fail closed, they do not error out.
func (q *Queries) GetValidatorTicketForUpdate(ctx context.Context, arg GetValidatorTicketForUpdateParams) (ValidatorTicket, error) {
	row := q.db.QueryRow(ctx, getValidatorTicketForUpdate, arg.AgentID, arg.BenchVersion, arg.ValidatorHotkey)
	var i ValidatorTicket
	err := row.Scan(
		&i.AgentID,
		&i.ValidatorHotkey,
		&i.Status,
		&i.IssuedAt,
		&i.Deadline,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BenchVersion,
		&i.AttemptCount,
		&i.RetryAfter,
		&i.ManualRetryGrants,
		&i.InfraRetryGrants,
		&i.SlotID,
		&i.Purpose,
		&i.LegacyCompletionAllowed,
		&i.PurposeRevision,
		&i.Seed,
		&i.DatasetSha256,
		&i.SeedBlock,
		&i.SeedBlockHash,
		&i.FailureReason,
		&i.FailedAt,
		&i.FirstReportedAt,
		&i.FailureDetail,
		&i.ContainerLogTail,
	)
	return i, err
}
