// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: validator_nonces_queries.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeValidatorNonce = `-- name: ConsumeValidatorNonce :exec

INSERT INTO validator_request_nonces (nonce, validator_hotkey, used_at, expires_at)
VALUES (
    $1::uuid,
    $2::text,
    $3::timestamptz,
    $4::timestamptz
)
`

type ConsumeValidatorNonceParams struct {
	Nonce           pgtype.UUID        `json:"nonce"`
	ValidatorHotkey string             `json:"validatorHotkey"`
	UsedAt          pgtype.Timestamptz `json:"usedAt"`
	ExpiresAt       pgtype.Timestamptz `json:"expiresAt"`
}

// Validator request nonces: the relay writes exactly one row per successful
// /exchange; the platform-role janitor prunes expired rows. The nonce PK is
// the single-use guard: a unique violation means replay, and the caller MUST
// run this inside a savepoint (pgx nested transaction) so the replay does
// not poison the outer /exchange transaction.
// Consume a validator request nonce. used_at/expires_at are computed by the
// application (now, now + exchange max age), matching the Python
// consume_validator_nonce. A duplicate-key error on the nonce PK signals a
// replayed exchange (mapped to HTTP 409 by the endpoint).
func (q *Queries) ConsumeValidatorNonce(ctx context.Context, arg ConsumeValidatorNonceParams) error {
	_, err := q.db.Exec(ctx, consumeValidatorNonce,
		arg.Nonce,
		arg.ValidatorHotkey,
		arg.UsedAt,
		arg.ExpiresAt,
	)
	return err
}
